/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleUSBCamera::MetaClass::MetaClass(AppleUSBCamera::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBCamera::MetaClass::~MetaClass(AppleUSBCamera::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *__hidden this); // idb
__int64 __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *__hidden this); // idb
void __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *this);
__int64 __fastcall AppleUSBCamera::getMetaClass(AppleUSBCamera *__hidden this); // idb
__int64 __fastcall AppleUSBCamera::MetaClass::MetaClass(AppleUSBCamera::MetaClass *__hidden this); // idb
IOService *__fastcall AppleUSBCamera::MetaClass::alloc(AppleUSBCamera::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1);
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1);
__int64 __fastcall AppleUSBCamera::start(AppleUSBCamera *__hidden this, IOService *); // idb
int __fastcall AppleUSBCamera::USBSend(__int64 a1, __int64 a2, char a3, __int16 a4, __int16 a5, __int16 a6, __int64 a7);
__int64 __fastcall AppleUSBCamera::MetaClass::~MetaClass(AppleUSBCamera::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
int _start();
int *OSKextGetCurrentIdentifier();
int *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall IOFree(_QWORD, _QWORD); weak
// int __fastcall IOMalloc(_QWORD); weak
// int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD __cdecl IOService::IOService(IOService *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOService::~IOService(IOService *__hidden this); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb
// void __cdecl bcopy(const void *, void *, size_t);

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_68 =
{
  {
    '_',
    '_',
    't',
    'e',
    'x',
    't',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  1904uLL,
  1975uLL,
  1904u,
  4u,
  0u,
  0u,
  2147484672u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_1000[4] = { 47416LL, 48160LL, 49728LL, 49744LL }; // weak
_QWORD off_1008[3] = { 48160LL, 49728LL, 49744LL }; // weak
__int64 off_1010[2] = { 49728LL, 49744LL }; // weak
__int64 off_1018 = 49744LL; // weak
__int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this) = { &AppleUSBCamera::~AppleUSBCamera, &AppleUSBCamera::~AppleUSBCamera }; // weak
__int64 (__fastcall *off_18C0[2])(AppleUSBCamera::MetaClass *__hidden this) =
{
  &AppleUSBCamera::MetaClass::~MetaClass,
  &AppleUSBCamera::MetaClass::~MetaClass
}; // weak
_QWORD gTheFirmware = 23589172418LL; // weak
__int16 word_19A8 = 768; // weak
int kmod_info = 0; // weak
_QWORD AppleUSBCamera::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak


//----- (0000000000000770) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::MetaClass::MetaClass(AppleUSBCamera::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBCamera", off_1008[0], 136LL);
  result = (__int64)off_18C0;
  *(_QWORD *)this = off_18C0;
  return result;
}
// 1008: using guessed type _QWORD off_1008[3];
// 18C0: using guessed type __int64 (__fastcall *off_18C0[2])(AppleUSBCamera::MetaClass *__hidden this);
// B980: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000007A2) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::MetaClass::~MetaClass(AppleUSBCamera::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (00000000000007AC) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this);

//----- (00000000000007CC) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this);

//----- (00000000000007EC) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *this)
{
  return IOService::~IOService(this);
}

//----- (00000000000007F6) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000800) ----------------------------------------------------
void __fastcall AppleUSBCamera::~AppleUSBCamera(AppleUSBCamera *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000822) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::getMetaClass(AppleUSBCamera *this)
{
  return (__int64)&AppleUSBCamera::gMetaClass;
}
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;

//----- (0000000000000830) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::MetaClass::MetaClass(AppleUSBCamera::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBCamera", off_1008[0], 136LL);
  result = (__int64)off_18C0;
  *(_QWORD *)this = off_18C0;
  return result;
}
// 1008: using guessed type _QWORD off_1008[3];
// 18C0: using guessed type __int64 (__fastcall *off_18C0[2])(AppleUSBCamera::MetaClass *__hidden this);
// B980: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000862) ----------------------------------------------------
IOService *__fastcall AppleUSBCamera::MetaClass::alloc(AppleUSBCamera::MetaClass *this, unsigned __int64 a2)
{
  IOService *v2; // rbx@1

  v2 = (IOService *)OSObject::operator new((OSObject *)&stru_68.addr, a2);
  IOService::IOService(v2, (const OSMetaClass *)&AppleUSBCamera::gMetaClass);
  *(_QWORD *)v2 = off_1050;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCamera::gMetaClass);
  return v2;
}
// 68: using guessed type section_64;
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this);
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;

//----- (00000000000008A2) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&AppleUSBCamera::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCamera::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this);
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;

//----- (00000000000008D2) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::AppleUSBCamera(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&AppleUSBCamera::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCamera::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBCamera *__hidden this);
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;

//----- (0000000000000902) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::start(AppleUSBCamera *this, IOService *a2)
{
  IOService *v2; // r15@1
  __int64 v3; // r13@1
  __int64 v4; // r14@1
  __int64 v5; // rax@2
  __int64 v6; // r12@2
  unsigned __int64 v7; // rbx@3
  char *v8; // rbx@5
  int v9; // eax@5
  __int64 v10; // rdx@5
  __int64 v11; // rcx@5
  int v12; // er12@5
  __int64 v13; // rax@6
  AppleUSBCamera *v14; // r12@6
  __int16 v15; // cx@7
  __int64 v16; // r12@8
  __int16 *v17; // r15@9
  __int64 v18; // rbx@9
  __int64 v19; // r12@9
  unsigned __int64 v20; // r12@10
  void *v21; // rax@10
  int v22; // eax@10
  __int64 v23; // rcx@10
  signed __int64 v24; // rax@12
  unsigned __int64 v25; // rax@13
  unsigned int v26; // er15@13
  __int64 v27; // rax@17
  int v28; // ebx@22
  __int64 v29; // rax@23
  __int64 v30; // rax@25
  __int64 v31; // rcx@25
  __int64 v32; // r9@25
  __int64 v33; // rdx@25
  __int64 v34; // rbx@28
  __int64 v36; // rax@34
  IOService *v37; // [sp+8h] [bp-2178h]@0
  signed __int64 v38; // [sp+10h] [bp-2170h]@13
  AppleUSBCamera *v39; // [sp+18h] [bp-2168h]@0
  __int64 v40; // [sp+20h] [bp-2160h]@7
  __int16 v41; // [sp+28h] [bp-2158h]@13
  int v42; // [sp+30h] [bp-2150h]@7
  __int64 v43; // [sp+30h] [bp-2150h]@13
  char v44; // [sp+38h] [bp-2148h]@5
  char v45; // [sp+39h] [bp-2147h]@5
  __int16 v46; // [sp+3Ah] [bp-2146h]@5
  __int16 v47; // [sp+3Ch] [bp-2144h]@5
  __int16 v48; // [sp+3Eh] [bp-2142h]@5
  char *v49; // [sp+40h] [bp-2140h]@5
  char v50; // [sp+50h] [bp-2130h]@5
  __int16 v51; // [sp+150h] [bp-2030h]@4
  __int16 v52[3]; // [sp+152h] [bp-202Eh]@4
  __int64 v53[1023]; // [sp+158h] [bp-2028h]@4
  __int64 v54; // [sp+2150h] [bp-30h]@1

  v2 = a2;
  LODWORD(v3) = (_DWORD)this;
  v4 = off_1018;
  v54 = *(_QWORD *)off_1018;
  if ( !(unsigned __int8)(*(int (**)(void))(off_1010[0] + 1488))() )
    goto LABEL_32;
  LODWORD(v5) = OSMetaClassBase::safeMetaCast(a2, *(_QWORD *)off_1000[0]);
  v6 = v5;
  if ( !v5 )
    goto LABEL_32;
  v7 = 0LL;
  if ( !(unsigned __int8)(*(int (__fastcall **)(IOService *, AppleUSBCamera *, _QWORD, _QWORD))(*(_QWORD *)a2 + 1488LL))(
                           a2,
                           this,
                           0LL,
                           0LL) )
    goto LABEL_32;
  do
  {
    *(__int16 *)((char *)&v51 + v7) = 0;
    v52[v7 / 2] = 0;
    v53[v7 / 8] = 0LL;
    v7 += 16LL;
  }
  while ( v7 != 0x2000 );
  v50 = 1;
  v44 = 64;
  v45 = -96;
  v46 = -6656;
  v47 = 0;
  v48 = 1;
  v8 = &v50;
  v49 = &v50;
  v9 = (*(int (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)v6 + 2360LL))(v6, &v44, 0LL);
  v11 = v6;
  v12 = v9;
  if ( v9 )
  {
    LODWORD(v13) = (*(int (__fastcall **)(AppleUSBCamera *, _QWORD, __int64, __int64))(*(_QWORD *)this + 904LL))(
                     this,
                     0LL,
                     v10,
                     v11);
    KernelDebugLogInternal(
      1LL,
      1431519814LL,
      "%s[%p]::start USBSend #1 returned 0x%x, firmware not downloaded",
      v13,
      this,
      (unsigned int)v12);
    v14 = this;
    LODWORD(v3) = 512;
  }
  else
  {
    v42 = 0;
    v40 = v11;
    v39 = this;
    v15 = __ROL2__(word_19A8, 8);
    v51 = v15;
    if ( word_19A8 == 384 )
    {
      v16 = v40;
    }
    else
    {
      v37 = a2;
      v17 = &v51;
      LODWORD(v18) = 8;
      v19 = 0LL;
      LODWORD(v3) = 0;
      do
      {
        v20 = 16 * v19;
        v52[v20 / 2] = (*((_BYTE *)&gTheFirmware + (unsigned int)(v18 + 2)) << 8) | *((_BYTE *)&gTheFirmware
                                                                                    + (unsigned int)(v18 + 3));
        LODWORD(v21) = IOMalloc((unsigned __int16)*v17);
        v53[v20 / 8] = (__int64)v21;
        bcopy((char *)&gTheFirmware + (unsigned int)(v18 + 4), v21, (unsigned __int16)*v17);
        v22 = (unsigned __int16)*v17;
        v23 = (unsigned int)(v22 + v18 + 5);
        v18 = (unsigned int)(v22 + v18 + 4);
        v3 = (unsigned int)(v3 + 1);
        LODWORD(v23) = (*((_BYTE *)&gTheFirmware + v18) << 8) | *((_BYTE *)&gTheFirmware + v23);
        v17 = &v51 + 8 * v3;
        *v17 = v23;
        v19 = v3;
      }
      while ( (unsigned __int16)v23 != 32769 );
      v4 = off_1018;
      v2 = a2;
      v16 = v40;
      v8 = &v50;
      if ( (_DWORD)v3 )
      {
        v24 = 0LL;
        do
        {
          v38 = v24;
          v25 = 16 * v24;
          LOWORD(v4) = v52[v25 / 2];
          v41 = v52[v25 / 2];
          v26 = *(unsigned __int16 *)((char *)&v51 + v25);
          v43 = v53[v25 / 8];
          if ( v26 < 0x33 )
          {
            v27 = 0LL;
          }
          else
          {
            v4 = 0LL;
            do
            {
              v44 = 64;
              v45 = -96;
              v46 = v41 + v4;
              v47 = 0;
              v48 = 50;
              v49 = (char *)(v43 + v4);
              if ( (*(int (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)v40 + 2360LL))(v40, &v44, 0LL) )
              {
                v14 = this;
                LODWORD(v30) = (*(int (__fastcall **)(AppleUSBCamera *, _QWORD))(*(_QWORD *)this + 904LL))(this, 0LL);
                v31 = v30;
                v32 = (unsigned __int16)(v41 + v4);
                v33 = (__int64)"%s[%p]::start USBSend #2 (%d) returned 0x%x";
                goto LABEL_26;
              }
              v4 += 50LL;
              v26 -= 50;
            }
            while ( v26 > 0x32 );
            v27 = (unsigned int)v4;
            LOWORD(v4) = v41 + v4;
          }
          v44 = 64;
          v45 = -96;
          v46 = v4;
          v47 = 0;
          v48 = v26;
          v49 = (char *)(v27 + v43);
          if ( (*(int (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)v40 + 2360LL))(v40, &v44, 0LL) )
            goto LABEL_34;
          v24 = v38 + 1;
          v8 = &v50;
        }
        while ( (signed int)v38 + 1 < (unsigned int)v3 );
        v42 = v3;
        v4 = off_1018;
        v2 = a2;
      }
    }
    v50 = 0;
    v44 = 64;
    v45 = -96;
    v46 = -6656;
    v47 = 0;
    v48 = 1;
    v49 = v8;
    v28 = (*(int (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)v16 + 2360LL))(v16, &v44, 0LL);
    if ( v28 )
    {
      v14 = this;
      LODWORD(v29) = (*(int (__fastcall **)(AppleUSBCamera *, _QWORD))(*(_QWORD *)this + 904LL))(this, 0LL);
      KernelDebugLogInternal(1LL, 1431519814LL, "%s[%p]::start USBSend #4 returned 0x%x", v29, this, (unsigned int)v28);
      LODWORD(v3) = v42;
    }
    else
    {
      LODWORD(v3) = v42;
      v14 = this;
    }
  }
  while ( 1 )
  {
    (*(void (__fastcall **)(IOService *, AppleUSBCamera *, _QWORD))(*(_QWORD *)v2 + 1496LL))(v2, v14, 0LL);
    if ( (_DWORD)v3 )
    {
      v34 = (__int64)v53;
      do
      {
        if ( *(_QWORD *)v34 )
          IOFree(*(_QWORD *)v34, *(_WORD *)(v34 - 8));
        v34 += 16LL;
        LODWORD(v3) = v3 - 1;
      }
      while ( (_DWORD)v3 );
    }
LABEL_32:
    if ( *(_QWORD *)v4 == v54 )
      break;
LABEL_34:
    v14 = v39;
    LODWORD(v36) = (*(int (__fastcall **)(AppleUSBCamera *, _QWORD))(*(_QWORD *)v39 + 904LL))(v39, 0LL);
    v31 = v36;
    v32 = (unsigned __int16)v4;
    v33 = (__int64)"%s[%p]::start USBSend #3 (%d) returned 0x%x";
LABEL_26:
    KernelDebugLogInternal(1LL, 1431519814LL, v33, v31, v14, v32);
    v4 = off_1018;
    v2 = v37;
  }
  return 0LL;
}
// 1000: using guessed type _QWORD off_1000[4];
// 1010: using guessed type __int64 off_1010[2];
// 1018: using guessed type __int64 off_1018;
// 19A0: using guessed type _QWORD gTheFirmware;
// 19A8: using guessed type __int16 word_19A8;
// B920: using guessed type int __fastcall IOFree(_QWORD, _QWORD);
// B928: using guessed type int __fastcall IOMalloc(_QWORD);
// B930: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// BB50: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// 902: using guessed type __int16 var_202E[3];
// 902: using guessed type __int64 var_2028[1023];

//----- (0000000000000E1E) ----------------------------------------------------
int __fastcall AppleUSBCamera::USBSend(__int64 a1, __int64 a2, char a3, __int16 a4, __int16 a5, __int16 a6, __int64 a7)
{
  char v8; // [sp+8h] [bp-18h]@1
  char v9; // [sp+9h] [bp-17h]@1
  __int16 v10; // [sp+Ah] [bp-16h]@1
  __int16 v11; // [sp+Ch] [bp-14h]@1
  __int16 v12; // [sp+Eh] [bp-12h]@1
  __int64 v13; // [sp+10h] [bp-10h]@1

  v8 = 64;
  v9 = a3;
  v10 = a4;
  v11 = a5;
  v12 = a6;
  v13 = a7;
  return (*(int (__fastcall **)(__int64, char *, _QWORD))(*(_QWORD *)a2 + 2360LL))(a2, &v8, 0LL);
}

//----- (0000000000000E5E) ----------------------------------------------------
__int64 __fastcall AppleUSBCamera::MetaClass::~MetaClass(AppleUSBCamera::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000E70) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(&AppleUSBCamera::gMetaClass, "AppleUSBCamera", off_1008[0], 136LL);
  result = (__int64)off_18C0;
  AppleUSBCamera::gMetaClass = off_18C0;
  return result;
}
// 1008: using guessed type _QWORD off_1008[3];
// 18C0: using guessed type __int64 (__fastcall *off_18C0[2])(AppleUSBCamera::MetaClass *__hidden this);
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;
// B980: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000EB0) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBCamera::gMetaClass);
}
// 44E0: using guessed type _QWORD AppleUSBCamera::gMetaClass;

//----- (0000000000000EC1) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 4508: using guessed type int (*_realmain)(void);

//----- (0000000000000EDB) ----------------------------------------------------
int *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 4;
}
// 4414: using guessed type int kmod_info;

//----- (0000000000000EEC) ----------------------------------------------------
int *OSKextGetCurrentVersionString()
{
  return &kmod_info + 20;
}
// 4414: using guessed type int kmod_info;

//----- (0000000000000EFD) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return (unsigned int)*(&kmod_info + 3);
}
// 4414: using guessed type int kmod_info;

//----- (0000000000000F0D) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 4510: using guessed type int (*_antimain)(void);

// ALL OK, 22 function(s) have been successfully decompiled
