/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleUSBMergeNub::MetaClass::MetaClass(AppleUSBMergeNub::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBMergeNub::MetaClass::~MetaClass(AppleUSBMergeNub::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *__hidden this); // idb
__int64 __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *__hidden this); // idb
void __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *this);
__int64 __fastcall AppleUSBMergeNub::getMetaClass(AppleUSBMergeNub *__hidden this); // idb
__int64 __fastcall AppleUSBMergeNub::MetaClass::MetaClass(AppleUSBMergeNub::MetaClass *__hidden this); // idb
IOService *__fastcall AppleUSBMergeNub::MetaClass::alloc(AppleUSBMergeNub::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1);
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1);
__int64 __fastcall AppleUSBMergeNub::probe(AppleUSBMergeNub *__hidden this, IOService *, int *); // idb
char __fastcall AppleUSBMergeNub::MergeDictionaryIntoProvider(__int64 a1, __int64 a2, __int64 a3);
char __fastcall AppleUSBMergeNub::MergeDictionaryIntoDictionary(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall AppleUSBMergeNub::MetaClass::~MetaClass(AppleUSBMergeNub::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
__int64 __fastcall AppleUSBiPod::MetaClass::MetaClass(AppleUSBiPod::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBiPod::MetaClass::~MetaClass(AppleUSBiPod::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *__hidden this); // idb
__int64 __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *__hidden this); // idb
void __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *this);
__int64 __fastcall AppleUSBiPod::getMetaClass(AppleUSBiPod *__hidden this); // idb
__int64 __fastcall AppleUSBiPod::MetaClass::MetaClass(AppleUSBiPod::MetaClass *__hidden this); // idb
IOUSBCompositeDriver *__fastcall AppleUSBiPod::MetaClass::alloc(AppleUSBiPod::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1);
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1);
int __fastcall AppleUSBiPod::start(AppleUSBiPod *this, IOService *a2);
__int64 __fastcall AppleUSBiPod::SendCommand(AppleUSBiPod *this, __int16 a2);
int __fastcall AppleUSBiPod::SetConfiguration(AppleUSBiPod *this, unsigned __int8 a2, unsigned __int8 a3);
int __fastcall AppleUSBiPod::willTerminate(AppleUSBiPod *this, IOService *a2, unsigned int a3);
int __fastcall AppleUSBiPod::message(AppleUSBiPod *this, unsigned int a2, __int64 a3, __int64 a4);
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::MetaClass(com_belkin_f2cd0007_adapter::MetaClass *__hidden this); // idb
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::~MetaClass(com_belkin_f2cd0007_adapter::MetaClass *__hidden this); // idb
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1, const OSMetaClass *a2);
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1, const OSMetaClass *a2);
__int64 __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *__hidden this); // idb
__int64 __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *__hidden this); // idb
void __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *this);
__int64 __fastcall com_belkin_f2cd0007_adapter::getMetaClass(com_belkin_f2cd0007_adapter *__hidden this); // idb
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::MetaClass(com_belkin_f2cd0007_adapter::MetaClass *__hidden this); // idb
IOUSBCompositeDriver *__fastcall com_belkin_f2cd0007_adapter::MetaClass::alloc(com_belkin_f2cd0007_adapter::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1);
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1);
__int64 __fastcall com_belkin_f2cd0007_adapter::SetConfiguration(com_belkin_f2cd0007_adapter *this, unsigned __int8 a2, unsigned __int8 a3);
int __fastcall com_belkin_f2cd0007_adapter::willTerminate(com_belkin_f2cd0007_adapter *this, IOService *a2, unsigned int a3);
__int64 __fastcall AppleUSBiPod::MetaClass::~MetaClass(AppleUSBiPod::MetaClass *__hidden this); // idb
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::~MetaClass(com_belkin_f2cd0007_adapter::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a_0();
__int64 `global destructor keyed to'_a_0();
int _start();
__int64 *OSKextGetCurrentIdentifier();
__int64 *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSDictionary::withDictionary(_QWORD, _QWORD); weak
// _QWORD __cdecl IORegistryEntry::getPlane(IORegistryEntry *__hidden this, const char *); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// _QWORD __cdecl IOUSBCompositeDriver::IOUSBCompositeDriver(IOUSBCompositeDriver *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *__hidden this); idb
// int __fastcall OSCollectionIterator::withCollection(_QWORD); weak
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD __cdecl IOService::IOService(IOService *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOService::~IOService(IOService *__hidden this); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_68 =
{
  {
    '_',
    '_',
    't',
    'e',
    'x',
    't',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  3472uLL,
  4131uLL,
  3472u,
  4u,
  0u,
  0u,
  2147484672u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_2000[8] = { 53864LL, 53960LL, 54472LL, 54720LL, 54880LL, 54896LL, 56472LL, 56480LL }; // weak
_QWORD off_2008[7] = { 53960LL, 54472LL, 54720LL, 54880LL, 54896LL, 56472LL, 56480LL }; // weak
_QWORD off_2010[6] = { 54472LL, 54720LL, 54880LL, 54896LL, 56472LL, 56480LL }; // weak
_QWORD off_2018[5] = { 54720LL, 54880LL, 54896LL, 56472LL, 56480LL }; // weak
_QWORD off_2020[4] = { 54880LL, 54896LL, 56472LL, 56480LL }; // weak
_QWORD off_2028[3] = { 54896LL, 56472LL, 56480LL }; // weak
__int64 off_2030[2] = { 56472LL, 56480LL }; // weak
__int64 off_2038 = 56480LL; // weak
__int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this) = { &AppleUSBMergeNub::~AppleUSBMergeNub, &AppleUSBMergeNub::~AppleUSBMergeNub }; // weak
__int64 (__fastcall *off_2900[2])(AppleUSBMergeNub::MetaClass *__hidden this) =
{
  &AppleUSBMergeNub::MetaClass::~MetaClass,
  &AppleUSBMergeNub::MetaClass::~MetaClass
}; // weak
__int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this) = { &AppleUSBiPod::~AppleUSBiPod, &AppleUSBiPod::~AppleUSBiPod }; // weak
__int64 (__fastcall *off_3320[2])(AppleUSBiPod::MetaClass *__hidden this) = { &AppleUSBiPod::MetaClass::~MetaClass, &AppleUSBiPod::MetaClass::~MetaClass }; // weak
__int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this) =
{
  &com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter,
  &com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter
}; // weak
__int64 (__fastcall *off_3D40[2])(com_belkin_f2cd0007_adapter::MetaClass *__hidden this) =
{
  &com_belkin_f2cd0007_adapter::MetaClass::~MetaClass,
  &com_belkin_f2cd0007_adapter::MetaClass::~MetaClass
}; // weak
__int64 kmod_info = 0LL; // weak
_QWORD AppleUSBMergeNub::gMetaClass; // weak
_QWORD AppleUSBiPod::gMetaClass; // weak
_QWORD com_belkin_f2cd0007_adapter::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak
_QWORD haveCreatedRef; // weak


//----- (0000000000000D90) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::MetaClass::MetaClass(AppleUSBMergeNub::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBMergeNub", off_2028[0], 136LL);
  result = (__int64)off_2900;
  *(_QWORD *)this = off_2900;
  return result;
}
// 2028: using guessed type _QWORD off_2028[3];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleUSBMergeNub::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000DC2) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::MetaClass::~MetaClass(AppleUSBMergeNub::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000DCC) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_2080;
  *(_QWORD *)a1 = off_2080;
  return result;
}
// 2080: using guessed type __int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this);

//----- (0000000000000DEC) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_2080;
  *(_QWORD *)a1 = off_2080;
  return result;
}
// 2080: using guessed type __int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this);

//----- (0000000000000E0C) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000E16) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000E20) ----------------------------------------------------
void __fastcall AppleUSBMergeNub::~AppleUSBMergeNub(AppleUSBMergeNub *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000E42) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::getMetaClass(AppleUSBMergeNub *this)
{
  return (__int64)&AppleUSBMergeNub::gMetaClass;
}
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;

//----- (0000000000000E50) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::MetaClass::MetaClass(AppleUSBMergeNub::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBMergeNub", off_2028[0], 136LL);
  result = (__int64)off_2900;
  *(_QWORD *)this = off_2900;
  return result;
}
// 2028: using guessed type _QWORD off_2028[3];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleUSBMergeNub::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000E82) ----------------------------------------------------
IOService *__fastcall AppleUSBMergeNub::MetaClass::alloc(AppleUSBMergeNub::MetaClass *this, unsigned __int64 a2)
{
  IOService *v2; // rbx@1

  v2 = (IOService *)OSObject::operator new((OSObject *)&stru_68.addr, a2);
  IOService::IOService(v2, (const OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
  *(_QWORD *)v2 = off_2080;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
  return v2;
}
// 68: using guessed type section_64;
// 2080: using guessed type __int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this);
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;

//----- (0000000000000EC2) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
  *(_QWORD *)a1 = off_2080;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
}
// 2080: using guessed type __int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this);
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;

//----- (0000000000000EF2) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::AppleUSBMergeNub(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
  *(_QWORD *)a1 = off_2080;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
}
// 2080: using guessed type __int64 (__fastcall *off_2080[2])(AppleUSBMergeNub *__hidden this);
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;

//----- (0000000000000F22) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::probe(AppleUSBMergeNub *this, IOService *a2, int *a3)
{
  __int64 v3; // r15@1
  __int64 v4; // rax@1
  __int64 v5; // rax@3
  __int64 v6; // rax@3
  __int64 v7; // r15@3
  __int64 v8; // rax@4
  __int64 v9; // rax@6

  v3 = IORegistryEntry::getPlane("IOUSB", (const char *)a2);
  LODWORD(v4) = OSMetaClassBase::safeMetaCast(a2, *(_QWORD *)off_2000[0]);
  if ( v4 )
  {
    if ( v3 )
    {
      LODWORD(v5) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v4 + 792LL))(v4, v3);
      LODWORD(v6) = OSMetaClassBase::safeMetaCast(v5, *(_QWORD *)off_2018[0]);
      v7 = v6;
      if ( v6 )
      {
        LODWORD(v8) = (*(int (__fastcall **)(AppleUSBMergeNub *, _QWORD))(*(_QWORD *)this + 696LL))(
                        this,
                        "IOProviderParentUSBNubMergeProperties");
        if ( v8 )
          (*(void (__fastcall **)(AppleUSBMergeNub *, __int64, __int64))(*(_QWORD *)this + 2128LL))(this, v7, v8);
      }
    }
  }
  LODWORD(v9) = (*(int (__fastcall **)(AppleUSBMergeNub *, _QWORD))(*(_QWORD *)this + 696LL))(
                  this,
                  "IOProviderMergeProperties");
  if ( v9 )
    (*(void (__fastcall **)(AppleUSBMergeNub *, IOService *, __int64))(*(_QWORD *)this + 2128LL))(this, a2, v9);
  return 0LL;
}
// 2000: using guessed type _QWORD off_2000[8];
// 2018: using guessed type _QWORD off_2018[5];
// D498: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000000FE8) ----------------------------------------------------
char __fastcall AppleUSBMergeNub::MergeDictionaryIntoProvider(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r15@1
  __int64 v4; // r12@1
  char result; // al@1
  OSMetaClass *v6; // rax@4
  __int64 v7; // rax@5
  __int64 v8; // rbx@5
  __int64 v9; // rax@6
  __int64 v10; // r13@6
  __int64 v11; // rax@8
  __int64 v12; // r15@8
  __int64 v13; // rax@9
  __int64 v14; // rax@10
  __int64 v15; // rax@10
  __int64 v16; // r12@10
  __int64 v17; // rax@12
  __int64 v18; // rbx@12
  int v19; // er14@13
  __int64 v20; // rax@15
  int (__fastcall *v21)(_QWORD, _QWORD, _QWORD); // r14@18
  __int64 v22; // rax@18
  __int64 v23; // rax@19
  char v24; // al@21
  __int64 v25; // rax@23
  __int64 v26; // [sp+0h] [bp-60h]@13
  __int64 v27; // [sp+8h] [bp-58h]@7
  __int64 v28; // [sp+10h] [bp-50h]@7
  __int64 v29; // [sp+18h] [bp-48h]@5
  char v30; // [sp+30h] [bp-30h]@7

  v3 = a3;
  v4 = a2;
  result = 0;
  if ( !a2 || !a3 )
    return result;
  if ( !(_BYTE)haveCreatedRef )
  {
    LOBYTE(haveCreatedRef) = 1;
    LODWORD(v6) = (*(int (**)(void))(*(_QWORD *)a1 + 56LL))();
    OSMetaClass::instanceConstructed(v6);
  }
  LODWORD(v7) = OSCollectionIterator::withCollection(v3);
  v8 = v7;
  v29 = v7;
  if ( !v7 )
  {
    v24 = 0;
    return v24 & 1;
  }
  LODWORD(v9) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v7 + 296LL))(v7);
  v10 = v9;
  if ( !v9 )
  {
    v30 = 0;
    goto LABEL_24;
  }
  v27 = v3;
  v28 = *(_QWORD *)off_2008[0];
  v30 = 0;
  while ( 1 )
  {
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v10 + 328LL))(v10);
    LODWORD(v11) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v4 + 680LL))(v4, v10);
    v12 = 0LL;
    if ( v11 )
    {
      LODWORD(v13) = OSMetaClassBase::safeMetaCast(v11, v28);
      v12 = v13;
    }
    LODWORD(v14) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v27 + 504LL))(v27, v10);
    LODWORD(v15) = OSMetaClassBase::safeMetaCast(v14, v28);
    v16 = v15;
    if ( !v12 || !v15 )
    {
      v4 = a2;
      v21 = *(int (__fastcall **)(_QWORD, _QWORD, _QWORD))(*(_QWORD *)a2 + 600LL);
      LODWORD(v22) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v27 + 504LL))(v27, v10);
      v30 = v21(a2, v10, v22);
      v8 = v29;
      if ( !v30 )
        goto LABEL_24;
      goto LABEL_19;
    }
    LODWORD(v17) = OSDictionary::withDictionary(v12, 0LL);
    v18 = v17;
    if ( !v17 )
      break;
    v19 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v12 + 312LL))(v12);
    v26 = v18;
    v30 = (*(int (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 2136LL))(a1, v16, v18);
    v8 = v29;
    v4 = a2;
    if ( !v30 )
      goto LABEL_24;
    if ( (*(int (__fastcall **)(__int64))(*(_QWORD *)v12 + 312LL))(v12) != v19 )
    {
      LODWORD(v20) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
      KernelDebugLogInternal(
        1LL,
        1431519814LL,
        "%s::MergeDictionaryIntoProvider  our provider's dictionary size changed (%d,%d)",
        v20);
    }
    v30 = (*(int (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a2 + 600LL))(a2, v10, v26);
    if ( !v30 )
      goto LABEL_24;
LABEL_19:
    LODWORD(v23) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v8 + 296LL))(v8);
    v10 = v23;
    if ( !v23 )
      goto LABEL_24;
  }
  LODWORD(v25) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
  KernelDebugLogInternal(
    1LL,
    1431519814LL,
    "%s::MergeDictionaryIntoProvider  could not copy our provider's dictionary",
    v25);
  v8 = v29;
LABEL_24:
  (*(void (__fastcall **)(__int64))(*(_QWORD *)v8 + 40LL))(v8);
  v24 = v30;
  return v24 & 1;
}
// 2008: using guessed type _QWORD off_2008[7];
// 3F68: using guessed type _QWORD haveCreatedRef;
// D260: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD);
// D2C0: using guessed type int __fastcall OSDictionary::withDictionary(_QWORD, _QWORD);
// D498: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// D5B8: using guessed type int __fastcall OSCollectionIterator::withCollection(_QWORD);

//----- (0000000000001254) ----------------------------------------------------
char __fastcall AppleUSBMergeNub::MergeDictionaryIntoDictionary(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rbx@1
  char result; // al@1
  __int64 v5; // rax@3
  __int64 v6; // rax@3
  signed __int64 v7; // rsi@3
  signed __int64 v8; // rax@3
  signed __int64 v9; // r13@3
  __int64 v10; // r12@4
  __int64 v11; // rax@5
  __int64 v12; // r15@5
  __int64 v13; // rax@6
  __int64 v14; // rax@7
  signed __int64 v15; // rax@7
  signed __int64 v16; // r12@7
  __int64 v17; // rax@9
  __int64 v18; // rbx@9
  int v19; // er14@10
  __int64 v20; // rax@12
  int (__fastcall *v21)(_QWORD, _QWORD, _QWORD); // r14@15
  __int64 v22; // rax@15
  __int64 v23; // rax@16
  signed __int64 v24; // rax@16
  __int64 v25; // rax@19
  __int64 v26; // [sp+0h] [bp-60h]@4
  __int64 v27; // [sp+10h] [bp-50h]@4
  signed __int64 v28; // [sp+18h] [bp-48h]@3
  __int64 v29; // [sp+20h] [bp-40h]@3
  char v30; // [sp+28h] [bp-38h]@4
  __int64 v31; // [sp+28h] [bp-38h]@11
  __int64 v32; // [sp+30h] [bp-30h]@1

  v3 = a3;
  v32 = a2;
  result = 0;
  if ( !a2 || !a3 )
    return result;
  LODWORD(v5) = OSCollectionIterator::withCollection(a2);
  v29 = v5;
  LODWORD(v6) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v5 + 296LL))(v5);
  v7 = *(_QWORD *)off_2020[0];
  v28 = *(_QWORD *)off_2020[0];
  LODWORD(v8) = OSMetaClassBase::safeMetaCast(v6, *(_QWORD *)off_2020[0]);
  v9 = v8;
  if ( !v8 )
  {
    v30 = 0;
    goto LABEL_20;
  }
  v26 = v3;
  v10 = *(_QWORD *)off_2008[0];
  v27 = *(_QWORD *)off_2008[0];
  v30 = 0;
  while ( 1 )
  {
    (*(void (__fastcall **)(signed __int64))(*(_QWORD *)v9 + 328LL))(v9);
    LODWORD(v11) = (*(int (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v3 + 504LL))(v3, v9);
    v12 = 0LL;
    if ( v11 )
    {
      LODWORD(v13) = OSMetaClassBase::safeMetaCast(v11, v10);
      v12 = v13;
    }
    LODWORD(v14) = (*(int (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v32 + 504LL))(v32, v9);
    LODWORD(v15) = OSMetaClassBase::safeMetaCast(v14, v10);
    v16 = v15;
    if ( !v12 || !v15 )
    {
      v21 = *(int (__fastcall **)(_QWORD, _QWORD, _QWORD))(*(_QWORD *)v3 + 448LL);
      LODWORD(v22) = (*(int (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v32 + 504LL))(v32, v9);
      v7 = v9;
      v30 = v21(v3, v9, v22);
      v10 = v27;
      if ( !v30 )
        goto LABEL_20;
      goto LABEL_16;
    }
    LODWORD(v17) = OSDictionary::withDictionary(v12, 0LL);
    v18 = v17;
    if ( !v17 )
      break;
    v19 = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v12 + 312LL))(v12, 0LL);
    v7 = v16;
    v30 = (*(int (__fastcall **)(__int64, signed __int64, __int64))(*(_QWORD *)a1 + 2136LL))(a1, v16, v18);
    v10 = v27;
    if ( !v30 )
      goto LABEL_20;
    v31 = v18;
    if ( (*(int (__fastcall **)(__int64))(*(_QWORD *)v12 + 312LL))(v12) != v19 )
    {
      LODWORD(v20) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
      KernelDebugLogInternal(
        1LL,
        1431519814LL,
        "%s::MergeDictionaryIntoDictionary  our target's dictionary size changed (%d,%d)",
        v20);
    }
    v3 = v26;
    v7 = v9;
    v30 = (*(int (__fastcall **)(__int64, signed __int64, __int64))(*(_QWORD *)v26 + 448LL))(v26, v9, v31);
    if ( !v30 )
      goto LABEL_20;
LABEL_16:
    LODWORD(v23) = (*(int (**)(void))(*(_QWORD *)v29 + 296LL))();
    v7 = v28;
    LODWORD(v24) = OSMetaClassBase::safeMetaCast(v23, v28);
    v9 = v24;
    if ( !v24 )
      goto LABEL_20;
  }
  LODWORD(v25) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
  v7 = 1431519814LL;
  KernelDebugLogInternal(
    1LL,
    1431519814LL,
    "%s::MergeDictionaryIntoDictionary  could not copy our target's dictionary",
    v25);
LABEL_20:
  (*(void (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v29 + 40LL))(v29, v7);
  return v30 & 1;
}
// 2008: using guessed type _QWORD off_2008[7];
// 2020: using guessed type _QWORD off_2020[4];
// D260: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD);
// D2C0: using guessed type int __fastcall OSDictionary::withDictionary(_QWORD, _QWORD);
// D498: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// D5B8: using guessed type int __fastcall OSCollectionIterator::withCollection(_QWORD);

//----- (000000000000149E) ----------------------------------------------------
__int64 __fastcall AppleUSBMergeNub::MetaClass::~MetaClass(AppleUSBMergeNub::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (00000000000014B0) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(&AppleUSBMergeNub::gMetaClass, "AppleUSBMergeNub", off_2028[0], 136LL);
  result = (__int64)off_2900;
  AppleUSBMergeNub::gMetaClass = off_2900;
  return result;
}
// 2028: using guessed type _QWORD off_2028[3];
// 2900: using guessed type __int64 (__fastcall *off_2900[2])(AppleUSBMergeNub::MetaClass *__hidden this);
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000014F0) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBMergeNub::gMetaClass);
}
// 3EE0: using guessed type _QWORD AppleUSBMergeNub::gMetaClass;

//----- (0000000000001510) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::MetaClass::MetaClass(AppleUSBiPod::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBiPod", off_2010[0], 176LL);
  result = (__int64)off_3320;
  *(_QWORD *)this = off_3320;
  return result;
}
// 2010: using guessed type _QWORD off_2010[6];
// 3320: using guessed type __int64 (__fastcall *off_3320[2])(AppleUSBiPod::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001542) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::MetaClass::~MetaClass(AppleUSBiPod::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (000000000000154C) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, a2);
  result = (__int64)off_2A00;
  *(_QWORD *)a1 = off_2A00;
  return result;
}
// 2A00: using guessed type __int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this);

//----- (000000000000156C) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, a2);
  result = (__int64)off_2A00;
  *(_QWORD *)a1 = off_2A00;
  return result;
}
// 2A00: using guessed type __int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this);

//----- (000000000000158C) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (0000000000001596) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (00000000000015A0) ----------------------------------------------------
void __fastcall AppleUSBiPod::~AppleUSBiPod(AppleUSBiPod *this)
{
  IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
  OSObject::operator delete((void *)this);
}

//----- (00000000000015C2) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::getMetaClass(AppleUSBiPod *this)
{
  return (__int64)&AppleUSBiPod::gMetaClass;
}
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;

//----- (00000000000015D0) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::MetaClass::MetaClass(AppleUSBiPod::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBiPod", off_2010[0], 176LL);
  result = (__int64)off_3320;
  *(_QWORD *)this = off_3320;
  return result;
}
// 2010: using guessed type _QWORD off_2010[6];
// 3320: using guessed type __int64 (__fastcall *off_3320[2])(AppleUSBiPod::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001602) ----------------------------------------------------
IOUSBCompositeDriver *__fastcall AppleUSBiPod::MetaClass::alloc(AppleUSBiPod::MetaClass *this, unsigned __int64 a2)
{
  IOUSBCompositeDriver *v2; // rbx@1

  v2 = (IOUSBCompositeDriver *)OSObject::operator new((OSObject *)&stru_68.reserved2, a2);
  IOUSBCompositeDriver::IOUSBCompositeDriver(v2, (const OSMetaClass *)&AppleUSBiPod::gMetaClass);
  *(_QWORD *)v2 = off_2A00;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBiPod::gMetaClass);
  return v2;
}
// 68: using guessed type section_64 stru_68;
// 2A00: using guessed type __int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this);
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;

//----- (0000000000001642) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, (const OSMetaClass *)&AppleUSBiPod::gMetaClass);
  *(_QWORD *)a1 = off_2A00;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBiPod::gMetaClass);
}
// 2A00: using guessed type __int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this);
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;

//----- (0000000000001672) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::AppleUSBiPod(IOUSBCompositeDriver *a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, (const OSMetaClass *)&AppleUSBiPod::gMetaClass);
  *(_QWORD *)a1 = off_2A00;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBiPod::gMetaClass);
}
// 2A00: using guessed type __int64 (__fastcall *off_2A00[2])(AppleUSBiPod *__hidden this);
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;

//----- (00000000000016A2) ----------------------------------------------------
int __fastcall AppleUSBiPod::start(AppleUSBiPod *this, IOService *a2)
{
  IOService *v2; // rbx@1
  AppleUSBiPod *v3; // r14@1
  signed __int64 v4; // r15@1
  IOService *v5; // rdi@1
  const char *v6; // rsi@1
  __int64 v7; // rax@1
  __int64 v8; // rax@4
  __int64 v9; // rax@5
  signed __int64 v10; // rsi@5
  __int64 v11; // rax@5
  __int64 v12; // rbx@5

  v2 = a2;
  v3 = this;
  v4 = *(_QWORD *)off_2000[0];
  v5 = a2;
  v6 = *(const char **)off_2000[0];
  LODWORD(v7) = OSMetaClassBase::safeMetaCast(v5, *(_QWORD *)off_2000[0]);
  *((_QWORD *)v3 + 17) = v7;
  if ( !v7 )
    return 0;
  if ( (unsigned __int16)(*(int (__fastcall **)(__int64, const char *))(*(_QWORD *)v7 + 2288LL))(v7, v6) == 1452
    && ((*(int (__cdecl **)(_QWORD))(**((_QWORD **)v3 + 17) + 2296LL))(*((_QWORD *)v3 + 17)) & 0xFFF0) == 4752 )
  {
    v8 = IORegistryEntry::getPlane("IOUSB", v6);
    if ( v8 )
    {
      LODWORD(v9) = (*(int (__fastcall **)(_QWORD, __int64))(**((_QWORD **)v3 + 17) + 792LL))(*((_QWORD *)v3 + 17), v8);
      v10 = v4;
      LODWORD(v11) = OSMetaClassBase::safeMetaCast(v9, v4);
      v12 = v11;
      if ( v11 )
      {
        (*(void (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v11 + 32LL))(v11, v4);
        if ( (unsigned __int16)(*(int (__fastcall **)(__int64))(*(_QWORD *)v12 + 2288LL))(v12) == 1452
          && (unsigned __int16)(*(int (__fastcall **)(__int64))(*(_QWORD *)v12 + 2296LL))(v12) == 37158 )
        {
          v10 = 400LL;
          AppleUSBiPod::SendCommand(v3, 400);
        }
        (*(void (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v12 + 40LL))(v12, v10);
      }
    }
    return 0;
  }
  return (*(int (__fastcall **)(AppleUSBiPod *, IOService *))(off_2030[0] + 1488))(v3, v2);
}
// 2000: using guessed type _QWORD off_2000[8];
// 2030: using guessed type __int64 off_2030[2];
// D498: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (00000000000017B6) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::SendCommand(AppleUSBiPod *this, __int16 a2)
{
  AppleUSBiPod *v2; // rbx@1
  int v3; // er14@1
  int v4; // eax@1
  __int64 v5; // rdi@1
  char v7; // [sp+8h] [bp-28h]@1
  char v8; // [sp+9h] [bp-27h]@1
  __int16 v9; // [sp+Ah] [bp-26h]@1
  __int16 v10; // [sp+Ch] [bp-24h]@1
  __int16 v11; // [sp+Eh] [bp-22h]@1
  __int64 v12; // [sp+10h] [bp-20h]@1

  v2 = this;
  v7 = 64;
  v8 = 64;
  v9 = 0;
  v10 = a2;
  v11 = 0;
  v12 = 0LL;
  v3 = 0;
  v4 = (*(int (__fastcall **)(_QWORD, char *, _QWORD))(**((_QWORD **)this + 17) + 2360LL))(
         *((_QWORD *)this + 17),
         &v7,
         0LL);
  v5 = *((_QWORD *)this + 17);
  if ( v4 )
    v3 = (*(int (__fastcall **)(__int64, signed __int64, _QWORD))(*(_QWORD *)v5 + 2504LL))(
           v5,
           6LL,
           *((_DWORD *)v2 + 42));
  else
    (*(void (__fastcall **)(__int64, _QWORD, _QWORD, signed __int64))(*(_QWORD *)v5 + 640LL))(
      v5,
      "Operating Current",
      (unsigned int)(*((_DWORD *)v2 + 42) + 500),
      32LL);
  return (unsigned int)v3;
}

//----- (000000000000184E) ----------------------------------------------------
int __fastcall AppleUSBiPod::SetConfiguration(AppleUSBiPod *this, unsigned __int8 a2, unsigned __int8 a3)
{
  unsigned __int8 v3; // r14@1
  int v4; // eax@1

  v3 = a3;
  v4 = (*(int (__fastcall **)(_QWORD, signed __int64, signed __int64))(**((_QWORD **)this + 17) + 2496LL))(
         *((_QWORD *)this + 17),
         6LL,
         500LL);
  *((_DWORD *)this + 42) = v4;
  if ( v4 )
  {
    if ( v4 == 500 )
    {
      AppleUSBiPod::SendCommand(this, 500);
    }
    else
    {
      (*(void (__fastcall **)(_QWORD, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2504LL))(
        *((_QWORD *)this + 17),
        6LL,
        (unsigned int)v4);
      *((_DWORD *)this + 42) = 0;
    }
  }
  return (*(int (__fastcall **)(AppleUSBiPod *, _QWORD, _QWORD))(off_2030[0] + 2160))(this, a2, v3);
}
// 2030: using guessed type __int64 off_2030[2];

//----- (00000000000018DE) ----------------------------------------------------
int __fastcall AppleUSBiPod::willTerminate(AppleUSBiPod *this, IOService *a2, unsigned int a3)
{
  unsigned int v3; // er14@1

  v3 = a3;
  if ( *((_DWORD *)this + 42) )
    (*(void (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)this + 17) + 2504LL))(*((_QWORD *)this + 17), 6LL);
  return (*(int (__fastcall **)(AppleUSBiPod *, IOService *, _QWORD))(off_2030[0] + 1040))(this, a2, v3);
}
// 2030: using guessed type __int64 off_2030[2];

//----- (0000000000001930) ----------------------------------------------------
int __fastcall AppleUSBiPod::message(AppleUSBiPod *this, unsigned int a2, __int64 a3, __int64 a4)
{
  __int64 v4; // r14@1
  __int64 v5; // r15@1

  v4 = a4;
  v5 = a3;
  if ( a2 == -536854518 )
    AppleUSBiPod::SendCommand(this, *((_DWORD *)this + 42));
  return (*(int (__fastcall **)(AppleUSBiPod *, _QWORD, __int64, __int64))(off_2030[0] + 1856))(this, a2, v5, v4);
}
// 2030: using guessed type __int64 off_2030[2];

//----- (0000000000001980) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::MetaClass(com_belkin_f2cd0007_adapter::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "com_belkin_f2cd0007_adapter", off_2010[0], 176LL);
  result = (__int64)off_3D40;
  *(_QWORD *)this = off_3D40;
  return result;
}
// 2010: using guessed type _QWORD off_2010[6];
// 3D40: using guessed type __int64 (__fastcall *off_3D40[2])(com_belkin_f2cd0007_adapter::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000019B2) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::~MetaClass(com_belkin_f2cd0007_adapter::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (00000000000019BC) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, a2);
  result = (__int64)off_3420;
  *(_QWORD *)a1 = off_3420;
  return result;
}
// 3420: using guessed type __int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this);

//----- (00000000000019DC) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, a2);
  result = (__int64)off_3420;
  *(_QWORD *)a1 = off_3420;
  return result;
}
// 3420: using guessed type __int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this);

//----- (00000000000019FC) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (0000000000001A06) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (0000000000001A10) ----------------------------------------------------
void __fastcall com_belkin_f2cd0007_adapter::~com_belkin_f2cd0007_adapter(com_belkin_f2cd0007_adapter *this)
{
  IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000001A32) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::getMetaClass(com_belkin_f2cd0007_adapter *this)
{
  return (__int64)&com_belkin_f2cd0007_adapter::gMetaClass;
}
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;

//----- (0000000000001A40) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::MetaClass(com_belkin_f2cd0007_adapter::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "com_belkin_f2cd0007_adapter", off_2010[0], 176LL);
  result = (__int64)off_3D40;
  *(_QWORD *)this = off_3D40;
  return result;
}
// 2010: using guessed type _QWORD off_2010[6];
// 3D40: using guessed type __int64 (__fastcall *off_3D40[2])(com_belkin_f2cd0007_adapter::MetaClass *__hidden this);
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001A72) ----------------------------------------------------
IOUSBCompositeDriver *__fastcall com_belkin_f2cd0007_adapter::MetaClass::alloc(com_belkin_f2cd0007_adapter::MetaClass *this, unsigned __int64 a2)
{
  IOUSBCompositeDriver *v2; // rbx@1

  v2 = (IOUSBCompositeDriver *)OSObject::operator new((OSObject *)&stru_68.reserved2, a2);
  IOUSBCompositeDriver::IOUSBCompositeDriver(v2, (const OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
  *(_QWORD *)v2 = off_3420;
  OSMetaClass::instanceConstructed((OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
  return v2;
}
// 68: using guessed type section_64 stru_68;
// 3420: using guessed type __int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this);
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;

//----- (0000000000001AB2) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, (const OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
  *(_QWORD *)a1 = off_3420;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
}
// 3420: using guessed type __int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this);
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;

//----- (0000000000001AE2) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::com_belkin_f2cd0007_adapter(IOUSBCompositeDriver *a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1, (const OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
  *(_QWORD *)a1 = off_3420;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
}
// 3420: using guessed type __int64 (__fastcall *off_3420[2])(com_belkin_f2cd0007_adapter *__hidden this);
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;

//----- (0000000000001B12) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::SetConfiguration(com_belkin_f2cd0007_adapter *this, unsigned __int8 a2, unsigned __int8 a3)
{
  unsigned __int8 v3; // r14@1
  int v4; // eax@1
  int v5; // er14@2
  __int64 v6; // rax@4
  __int64 v7; // rax@4
  __int64 v8; // r15@4

  v3 = a3;
  v4 = (*(int (__fastcall **)(_QWORD, signed __int64, signed __int64))(**((_QWORD **)this + 17) + 2496LL))(
         *((_QWORD *)this + 17),
         1LL,
         500LL);
  *((_DWORD *)this + 42) = v4;
  if ( v4 == 500 )
  {
    v5 = (*(int (__fastcall **)(com_belkin_f2cd0007_adapter *, _QWORD, _QWORD))(off_2030[0] + 2160))(this, a2, v3);
    if ( !v5 )
    {
      (*(void (__fastcall **)(_QWORD, _QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 640LL))(
        *((_QWORD *)this + 17),
        "Operating Current",
        (unsigned int)(*((_DWORD *)this + 42) + 500),
        32LL);
      v5 = 0;
    }
  }
  else
  {
    (*(void (__fastcall **)(_QWORD, signed __int64, _QWORD))(**((_QWORD **)this + 17) + 2504LL))(
      *((_QWORD *)this + 17),
      1LL,
      (unsigned int)v4);
    *((_DWORD *)this + 42) = 0;
    v5 = 0;
    LODWORD(v6) = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 904LL))(
                    *((_QWORD *)this + 17),
                    0LL);
    KernelDebugLogInternal(
      1LL,
      1431519814LL,
      "USB Low Power Notice:  The device \"%s\" cannot be used because there is not enough extra current to enable it",
      v6);
    LODWORD(v7) = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)this + 17) + 696LL))(
                    *((_QWORD *)this + 17),
                    "Low Power Displayed");
    v8 = *(_QWORD *)off_2038;
    if ( v7 != **(_QWORD **)off_2038 )
    {
      (*(void (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)this + 17) + 2456LL))(*((_QWORD *)this + 17), 1LL);
      (*(void (__fastcall **)(_QWORD, _QWORD, _QWORD))(**((_QWORD **)this + 17) + 616LL))(
        *((_QWORD *)this + 17),
        "Low Power Displayed",
        *(_QWORD *)v8);
    }
  }
  return (unsigned int)v5;
}
// 2030: using guessed type __int64 off_2030[2];
// 2038: using guessed type __int64 off_2038;
// D260: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001C54) ----------------------------------------------------
int __fastcall com_belkin_f2cd0007_adapter::willTerminate(com_belkin_f2cd0007_adapter *this, IOService *a2, unsigned int a3)
{
  unsigned int v3; // er14@1

  v3 = a3;
  if ( *((_DWORD *)this + 42) )
    (*(void (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)this + 17) + 2504LL))(*((_QWORD *)this + 17), 1LL);
  return (*(int (__fastcall **)(com_belkin_f2cd0007_adapter *, IOService *, _QWORD))(off_2030[0] + 1040))(this, a2, v3);
}
// 2030: using guessed type __int64 off_2030[2];

//----- (0000000000001CA6) ----------------------------------------------------
__int64 __fastcall AppleUSBiPod::MetaClass::~MetaClass(AppleUSBiPod::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000001CB0) ----------------------------------------------------
__int64 __fastcall com_belkin_f2cd0007_adapter::MetaClass::~MetaClass(com_belkin_f2cd0007_adapter::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000001CC0) ----------------------------------------------------
__int64 `global constructor keyed to'_a_0()
{
  __int64 v0; // rbx@1
  __int64 result; // rax@1

  v0 = off_2010[0];
  OSMetaClass::OSMetaClass(&AppleUSBiPod::gMetaClass, "AppleUSBiPod", off_2010[0], 176LL);
  AppleUSBiPod::gMetaClass = off_3320;
  OSMetaClass::OSMetaClass(&com_belkin_f2cd0007_adapter::gMetaClass, "com_belkin_f2cd0007_adapter", v0, 176LL);
  result = (__int64)off_3D40;
  com_belkin_f2cd0007_adapter::gMetaClass = off_3D40;
  return result;
}
// 2010: using guessed type _QWORD off_2010[6];
// 3320: using guessed type __int64 (__fastcall *off_3320[2])(AppleUSBiPod::MetaClass *__hidden this);
// 3D40: using guessed type __int64 (__fastcall *off_3D40[2])(com_belkin_f2cd0007_adapter::MetaClass *__hidden this);
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;
// D2B0: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001D30) ----------------------------------------------------
__int64 `global destructor keyed to'_a_0()
{
  OSMetaClass::~OSMetaClass((OSMetaClass *)&com_belkin_f2cd0007_adapter::gMetaClass);
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBiPod::gMetaClass);
}
// 3F08: using guessed type _QWORD AppleUSBiPod::gMetaClass;
// 3F30: using guessed type _QWORD com_belkin_f2cd0007_adapter::gMetaClass;

//----- (0000000000001D4D) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 3F58: using guessed type int (*_realmain)(void);

//----- (0000000000001D67) ----------------------------------------------------
__int64 *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 2;
}
// 3E18: using guessed type __int64 kmod_info;

//----- (0000000000001D78) ----------------------------------------------------
__int64 *OSKextGetCurrentVersionString()
{
  return &kmod_info + 10;
}
// 3E18: using guessed type __int64 kmod_info;

//----- (0000000000001D89) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *((_DWORD *)&kmod_info + 3);
}
// 3E18: using guessed type __int64 kmod_info;

//----- (0000000000001D99) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 3F60: using guessed type int (*_antimain)(void);

// ALL OK, 58 function(s) have been successfully decompiled
