/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleUSBOpticalMouse::MetaClass::MetaClass(AppleUSBOpticalMouse::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::~MetaClass(AppleUSBOpticalMouse::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1, const OSMetaClass *a2);
__int64 __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *__hidden this); // idb
__int64 __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *__hidden this); // idb
void __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *this);
__int64 __fastcall AppleUSBOpticalMouse::getMetaClass(AppleUSBOpticalMouse *__hidden this); // idb
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::MetaClass(AppleUSBOpticalMouse::MetaClass *__hidden this); // idb
IOUSBHIDDriver *__fastcall AppleUSBOpticalMouse::MetaClass::alloc(AppleUSBOpticalMouse::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1);
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1);
__int64 __fastcall AppleUSBOpticalMouse::StartFinalProcessing(AppleUSBOpticalMouse *__hidden this); // idb
int AppleUSBOpticalMouse::willTerminate();
int __fastcall AppleUSBOpticalMouse::setPowerState(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::~MetaClass(AppleUSBOpticalMouse::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
int _start();
__int64 *OSKextGetCurrentIdentifier();
__int64 *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// _QWORD __cdecl IOUSBHIDDriver::IOUSBHIDDriver(IOUSBHIDDriver *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOUSBHIDDriver::~IOUSBHIDDriver(IOUSBHIDDriver *__hidden this); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_150 =
{
  {
    '_',
    '_',
    'g',
    'o',
    't',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__DATA",
  4096uLL,
  32uLL,
  4096u,
  3u,
  0u,
  0u,
  0u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_1000[4] = { 42080LL, 42912LL, 44640LL, 44648LL }; // weak
_QWORD off_1008[3] = { 42912LL, 44640LL, 44648LL }; // weak
__int64 off_1010[2] = { 44640LL, 44648LL }; // weak
__int64 off_1018 = 44648LL; // weak
__int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this) =
{
  &AppleUSBOpticalMouse::~AppleUSBOpticalMouse,
  &AppleUSBOpticalMouse::~AppleUSBOpticalMouse
}; // weak
__int64 (__fastcall *off_1B80[2])(AppleUSBOpticalMouse::MetaClass *__hidden this) =
{
  &AppleUSBOpticalMouse::MetaClass::~MetaClass,
  &AppleUSBOpticalMouse::MetaClass::~MetaClass
}; // weak
__int64 kmod_info = 0LL; // weak
_QWORD AppleUSBOpticalMouse::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak
_QWORD switchTo800dpi; // weak


//----- (0000000000000A80) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::MetaClass(AppleUSBOpticalMouse::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBOpticalMouse", off_1000[0], 360LL);
  result = (__int64)off_1B80;
  *(_QWORD *)this = off_1B80;
  return result;
}
// 1000: using guessed type _QWORD off_1000[4];
// 1B80: using guessed type __int64 (__fastcall *off_1B80[2])(AppleUSBOpticalMouse::MetaClass *__hidden this);
// A450: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000AB2) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::~MetaClass(AppleUSBOpticalMouse::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000ABC) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBHIDDriver::IOUSBHIDDriver(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this);

//----- (0000000000000ADC) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOUSBHIDDriver::IOUSBHIDDriver(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this);

//----- (0000000000000AFC) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *this)
{
  return IOUSBHIDDriver::~IOUSBHIDDriver(this);
}

//----- (0000000000000B06) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *this)
{
  return IOUSBHIDDriver::~IOUSBHIDDriver(this);
}

//----- (0000000000000B10) ----------------------------------------------------
void __fastcall AppleUSBOpticalMouse::~AppleUSBOpticalMouse(AppleUSBOpticalMouse *this)
{
  IOUSBHIDDriver::~IOUSBHIDDriver(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000B32) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::getMetaClass(AppleUSBOpticalMouse *this)
{
  return (__int64)&AppleUSBOpticalMouse::gMetaClass;
}
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;

//----- (0000000000000B40) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::MetaClass(AppleUSBOpticalMouse::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBOpticalMouse", off_1000[0], 360LL);
  result = (__int64)off_1B80;
  *(_QWORD *)this = off_1B80;
  return result;
}
// 1000: using guessed type _QWORD off_1000[4];
// 1B80: using guessed type __int64 (__fastcall *off_1B80[2])(AppleUSBOpticalMouse::MetaClass *__hidden this);
// A450: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000B72) ----------------------------------------------------
IOUSBHIDDriver *__fastcall AppleUSBOpticalMouse::MetaClass::alloc(AppleUSBOpticalMouse::MetaClass *this, unsigned __int64 a2)
{
  IOUSBHIDDriver *v2; // rbx@1

  v2 = (IOUSBHIDDriver *)OSObject::operator new((OSObject *)&stru_150.segname[8], a2);
  IOUSBHIDDriver::IOUSBHIDDriver(v2, (const OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
  *(_QWORD *)v2 = off_1050;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
  return v2;
}
// 150: using guessed type section_64;
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this);
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;

//----- (0000000000000BB2) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1)
{
  IOUSBHIDDriver::IOUSBHIDDriver(a1, (const OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this);
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;

//----- (0000000000000BE2) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::AppleUSBOpticalMouse(IOUSBHIDDriver *a1)
{
  IOUSBHIDDriver::IOUSBHIDDriver(a1, (const OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(AppleUSBOpticalMouse *__hidden this);
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;

//----- (0000000000000C12) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::StartFinalProcessing(AppleUSBOpticalMouse *this)
{
  __int64 v1; // rax@1
  __int64 v2; // rbx@1
  __int64 v3; // rax@1
  int v4; // er14@1
  bool v5; // zf@1
  __int64 v6; // rax@6
  __int64 v7; // r13@6
  __int64 v8; // r12@6
  __int64 v9; // rax@6
  int v10; // ebx@6
  __int64 v11; // rax@10
  __int64 v12; // r13@10
  __int64 v13; // rax@10
  int v14; // er12@10
  int v15; // eax@15
  char v17; // [sp+8h] [bp-58h]@17
  char v18; // [sp+9h] [bp-57h]@17
  __int16 v19; // [sp+Ah] [bp-56h]@17
  __int16 v20; // [sp+Ch] [bp-54h]@17
  __int16 v21; // [sp+Eh] [bp-52h]@17
  __int64 v22; // [sp+10h] [bp-50h]@17
  char v23; // [sp+20h] [bp-40h]@2
  char v24; // [sp+21h] [bp-3Fh]@2
  __int16 v25; // [sp+22h] [bp-3Eh]@2
  __int16 v26; // [sp+24h] [bp-3Ch]@2
  __int16 v27; // [sp+26h] [bp-3Ah]@2
  __int64 v28; // [sp+28h] [bp-38h]@2

  *((_BYTE *)this + 354) = 0;
  LODWORD(v1) = (*(int (__fastcall **)(AppleUSBOpticalMouse *, _QWORD))(*(_QWORD *)this + 696LL))(
                  this,
                  "SwitchTo800DPI");
  v2 = *(_QWORD *)off_1018;
  *((_BYTE *)this + 352) = v1 == **(_QWORD **)off_1018;
  LODWORD(v3) = (*(int (__fastcall **)(AppleUSBOpticalMouse *, _QWORD))(*(_QWORD *)this + 696LL))(
                  this,
                  "SwitchTo2000FPS");
  v4 = 0;
  v5 = v3 == *(_QWORD *)v2;
  *((_BYTE *)this + 353) = v3 == *(_QWORD *)v2;
  if ( v5 )
  {
    v23 = 64;
    v24 = 1;
    v25 = 1452;
    v26 = -10224;
    v27 = 0;
    v28 = 0LL;
    if ( !(*(int (__fastcall **)(_QWORD, char *, signed __int64, _QWORD, _QWORD))(**((_QWORD **)this + 27) + 2424LL))(
            *((_QWORD *)this + 27),
            &v23,
            5000LL,
            0LL,
            0LL) )
    {
      v23 = 64;
      v24 = 1;
      v25 = 1452;
      v26 = -9199;
      v27 = 0;
      v28 = 0LL;
      (*(void (__fastcall **)(_QWORD, char *, signed __int64, _QWORD, _QWORD))(**((_QWORD **)this + 27) + 2424LL))(
        *((_QWORD *)this + 27),
        &v23,
        5000LL,
        0LL,
        0LL);
    }
    v4 = (*(int (__fastcall **)(AppleUSBOpticalMouse *))(off_1010[0] + 2680))(this);
  }
  if ( *((_BYTE *)this + 352) )
  {
    LODWORD(v6) = (*(int (__fastcall **)(AppleUSBOpticalMouse *, _QWORD))(*(_QWORD *)this + 744LL))(
                    this,
                    "HIDPointerResolution");
    v7 = v6;
    v8 = *(_QWORD *)off_1008[0];
    LODWORD(v9) = OSMetaClassBase::safeMetaCast(v6, *(_QWORD *)off_1008[0]);
    v10 = 26214400;
    if ( v9 )
      v10 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v9 + 328LL))(v9);
    if ( v7 )
      (*(void (__fastcall **)(__int64))(*(_QWORD *)v7 + 40LL))(v7);
    LODWORD(v11) = (*(int (__fastcall **)(AppleUSBOpticalMouse *, _QWORD))(*(_QWORD *)this + 744LL))(
                     this,
                     "xResolutionPref");
    v12 = v11;
    LODWORD(v13) = OSMetaClassBase::safeMetaCast(v11, v8);
    v14 = 52428800;
    if ( v13 )
      v14 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v13 + 328LL))(v13);
    if ( v12 )
      (*(void (__fastcall **)(__int64))(*(_QWORD *)v12 + 40LL))(v12);
    if ( v14 == v10 )
    {
      *((_BYTE *)this + 354) = 1;
      v15 = (*(int (__fastcall **)(AppleUSBOpticalMouse *))(off_1010[0] + 2680))(this);
LABEL_18:
      v4 = v15;
      return (unsigned int)v4;
    }
    if ( !(_BYTE)switchTo800dpi )
    {
      v17 = 64;
      v18 = 1;
      v19 = 1452;
      v20 = 1106;
      v21 = 0;
      v22 = 0LL;
      v15 = (*(int (__fastcall **)(_QWORD, char *, signed __int64, _QWORD, _QWORD))(**((_QWORD **)this + 27) + 2424LL))(
              *((_QWORD *)this + 27),
              &v17,
              5000LL,
              0LL,
              0LL);
      goto LABEL_18;
    }
  }
  return (unsigned int)v4;
}
// 1008: using guessed type _QWORD off_1008[3];
// 1010: using guessed type __int64 off_1010[2];
// 1018: using guessed type __int64 off_1018;
// 1D58: using guessed type _QWORD switchTo800dpi;
// A770: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000000E3A) ----------------------------------------------------
int AppleUSBOpticalMouse::willTerminate()
{
  return (*(int (**)(void))(off_1010[0] + 1040))();
}
// 1010: using guessed type __int64 off_1010[2];

//----- (0000000000000E4C) ----------------------------------------------------
int __fastcall AppleUSBOpticalMouse::setPowerState(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r14@1
  char v5; // [sp+0h] [bp-30h]@3
  char v6; // [sp+1h] [bp-2Fh]@3
  __int16 v7; // [sp+2h] [bp-2Eh]@3
  __int16 v8; // [sp+4h] [bp-2Ch]@3
  __int16 v9; // [sp+6h] [bp-2Ah]@3
  __int64 v10; // [sp+8h] [bp-28h]@3

  v3 = a3;
  if ( a2 == 1 && *(_BYTE *)(a1 + 354) )
  {
    LOBYTE(switchTo800dpi) = 1;
    v5 = 64;
    v6 = 1;
    v7 = 1452;
    v8 = 82;
    v9 = 0;
    v10 = 0LL;
    (*(void (__fastcall **)(_QWORD, char *, signed __int64, _QWORD, _QWORD))(**(_QWORD **)(a1 + 216) + 2424LL))(
      *(_QWORD *)(a1 + 216),
      &v5,
      5000LL,
      0LL,
      0LL);
  }
  return (*(int (__fastcall **)(__int64, __int64, __int64))(off_1010[0] + 2040))(a1, a2, v3);
}
// 1010: using guessed type __int64 off_1010[2];
// 1D58: using guessed type _QWORD switchTo800dpi;

//----- (0000000000000EDA) ----------------------------------------------------
__int64 __fastcall AppleUSBOpticalMouse::MetaClass::~MetaClass(AppleUSBOpticalMouse::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000EF0) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(&AppleUSBOpticalMouse::gMetaClass, "AppleUSBOpticalMouse", off_1000[0], 360LL);
  result = (__int64)off_1B80;
  AppleUSBOpticalMouse::gMetaClass = off_1B80;
  return result;
}
// 1000: using guessed type _QWORD off_1000[4];
// 1B80: using guessed type __int64 (__fastcall *off_1B80[2])(AppleUSBOpticalMouse::MetaClass *__hidden this);
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;
// A450: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000F30) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBOpticalMouse::gMetaClass);
}
// 1D20: using guessed type _QWORD AppleUSBOpticalMouse::gMetaClass;

//----- (0000000000000F41) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 1D48: using guessed type int (*_realmain)(void);

//----- (0000000000000F5B) ----------------------------------------------------
__int64 *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 2;
}
// 1C58: using guessed type __int64 kmod_info;

//----- (0000000000000F6C) ----------------------------------------------------
__int64 *OSKextGetCurrentVersionString()
{
  return &kmod_info + 10;
}
// 1C58: using guessed type __int64 kmod_info;

//----- (0000000000000F7D) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *((_DWORD *)&kmod_info + 3);
}
// 1C58: using guessed type __int64 kmod_info;

//----- (0000000000000F8D) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 1D50: using guessed type int (*_antimain)(void);

// ALL OK, 23 function(s) have been successfully decompiled
