/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall IOUSBUserClientInit::MetaClass::MetaClass(IOUSBUserClientInit::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBUserClientInit::MetaClass::~MetaClass(IOUSBUserClientInit::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1, const OSMetaClass *a2);
__int64 __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *__hidden this); // idb
__int64 __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *__hidden this); // idb
void __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *this);
__int64 __fastcall IOUSBUserClientInit::getMetaClass(IOUSBUserClientInit *__hidden this); // idb
__int64 __fastcall IOUSBUserClientInit::MetaClass::MetaClass(IOUSBUserClientInit::MetaClass *__hidden this); // idb
IOService *__fastcall IOUSBUserClientInit::MetaClass::alloc(IOUSBUserClientInit::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1);
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1);
__int64 __fastcall IOUSBUserClientInit::start(IOUSBUserClientInit *__hidden this, IOService *); // idb
char __fastcall IOUSBUserClientInit::MergeDictionaryIntoProvider(__int64 a1, __int64 a2, __int64 a3);
bool __fastcall IOUSBUserClientInit::MergeDictionaryIntoDictionary(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall IOUSBUserClientInit::MetaClass::~MetaClass(IOUSBUserClientInit::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
int _start();
__int64 *OSKextGetCurrentIdentifier();
__int64 *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSDictionary::withDictionary(_QWORD, _QWORD); weak
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// int __fastcall OSCollectionIterator::withCollection(_QWORD); weak
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD __cdecl IOService::IOService(IOService *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOService::~IOService(IOService *__hidden this); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_68 =
{
  {
    '_',
    '_',
    't',
    'e',
    'x',
    't',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  2192uLL,
  1655uLL,
  2192u,
  4u,
  0u,
  0u,
  2147484672u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_1000[3] = { 35376LL, 36040LL, 36056LL }; // weak
_QWORD off_1008[2] = { 36040LL, 36056LL }; // weak
_QWORD off_1010 = 36056LL; // weak
__int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this) =
{
  &IOUSBUserClientInit::~IOUSBUserClientInit,
  &IOUSBUserClientInit::~IOUSBUserClientInit
}; // weak
__int64 (__fastcall *off_18D0[2])(IOUSBUserClientInit::MetaClass *__hidden this) =
{
  &IOUSBUserClientInit::MetaClass::~MetaClass,
  &IOUSBUserClientInit::MetaClass::~MetaClass
}; // weak
__int64 kmod_info = 0LL; // weak
_QWORD IOUSBUserClientInit::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak
_QWORD gInstances; // weak


//----- (0000000000000890) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::MetaClass::MetaClass(IOUSBUserClientInit::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "IOUSBUserClientInit", off_1010, 136LL);
  result = (__int64)off_18D0;
  *(_QWORD *)this = off_18D0;
  return result;
}
// 1010: using guessed type _QWORD off_1010;
// 18D0: using guessed type __int64 (__fastcall *off_18D0[2])(IOUSBUserClientInit::MetaClass *__hidden this);
// 8A18: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000008C2) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::MetaClass::~MetaClass(IOUSBUserClientInit::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (00000000000008CC) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this);

//----- (00000000000008EC) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOService::IOService(a1, a2);
  result = (__int64)off_1050;
  *(_QWORD *)a1 = off_1050;
  return result;
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this);

//----- (000000000000090C) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000916) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000000920) ----------------------------------------------------
void __fastcall IOUSBUserClientInit::~IOUSBUserClientInit(IOUSBUserClientInit *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000942) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::getMetaClass(IOUSBUserClientInit *this)
{
  return (__int64)&IOUSBUserClientInit::gMetaClass;
}
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;

//----- (0000000000000950) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::MetaClass::MetaClass(IOUSBUserClientInit::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "IOUSBUserClientInit", off_1010, 136LL);
  result = (__int64)off_18D0;
  *(_QWORD *)this = off_18D0;
  return result;
}
// 1010: using guessed type _QWORD off_1010;
// 18D0: using guessed type __int64 (__fastcall *off_18D0[2])(IOUSBUserClientInit::MetaClass *__hidden this);
// 8A18: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000982) ----------------------------------------------------
IOService *__fastcall IOUSBUserClientInit::MetaClass::alloc(IOUSBUserClientInit::MetaClass *this, unsigned __int64 a2)
{
  IOService *v2; // rbx@1

  v2 = (IOService *)OSObject::operator new((OSObject *)&stru_68.addr, a2);
  IOService::IOService(v2, (const OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
  *(_QWORD *)v2 = off_1050;
  OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
  return v2;
}
// 68: using guessed type section_64 stru_68;
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this);
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;

//----- (00000000000009C2) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this);
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;

//----- (00000000000009F2) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::IOUSBUserClientInit(IOService *a1)
{
  IOService::IOService(a1, (const OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
  *(_QWORD *)a1 = off_1050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
}
// 1050: using guessed type __int64 (__fastcall *off_1050[2])(IOUSBUserClientInit *__hidden this);
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;

//----- (0000000000000A22) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::start(IOUSBUserClientInit *this, IOService *a2)
{
  int v2; // eax@1
  __int64 v3; // rax@3
  __int64 v4; // rax@3
  __int64 v5; // rax@4

  v2 = gInstances;
  LODWORD(gInstances) = gInstances + 1;
  if ( !v2 )
    (*(void (**)(void))(*(_QWORD *)this + 32LL))();
  LODWORD(v3) = (*(int (__fastcall **)(IOUSBUserClientInit *, _QWORD))(*(_QWORD *)this + 696LL))(
                  this,
                  "IOProviderMergeProperties");
  LODWORD(v4) = OSMetaClassBase::safeMetaCast(v3, *(_QWORD *)off_1000[0]);
  if ( v4 )
  {
    (*(void (__fastcall **)(IOUSBUserClientInit *, IOService *, __int64))(*(_QWORD *)this + 2128LL))(this, a2, v4);
    LODWORD(v5) = (*(int (__fastcall **)(IOService *, _QWORD))(*(_QWORD *)a2 + 696LL))(a2, "IOUSBUserClientClass");
    if ( v5 )
      (*(void (__fastcall **)(IOService *, _QWORD, __int64))(*(_QWORD *)a2 + 616LL))(a2, "IOUserClientClass", v5);
  }
  return 0LL;
}
// 1000: using guessed type _QWORD off_1000[3];
// 1AA8: using guessed type _QWORD gInstances;
// 8BF8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000000ABC) ----------------------------------------------------
char __fastcall IOUSBUserClientInit::MergeDictionaryIntoProvider(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rbx@1
  __int64 v4; // r12@1
  char v5; // r14@1
  __int64 v6; // rax@3
  __int64 v7; // rax@4
  __int64 v8; // r13@4
  char v9; // r14@5
  __int64 v10; // rax@6
  __int64 v11; // r15@6
  __int64 v12; // rax@7
  __int64 v13; // rax@8
  __int64 v14; // rax@8
  __int64 v15; // r12@8
  __int64 v16; // rax@10
  __int64 v17; // r14@11
  int v18; // ebx@11
  __int64 v19; // rax@13
  char v20; // al@14
  int (__fastcall *v21)(_QWORD, _QWORD, _QWORD); // r14@15
  __int64 v22; // rax@15
  __int64 v23; // rax@17
  __int64 v24; // rax@21
  __int64 v26; // [sp+8h] [bp-58h]@11
  __int64 v27; // [sp+10h] [bp-50h]@5
  __int64 v28; // [sp+18h] [bp-48h]@5
  __int64 v29; // [sp+28h] [bp-38h]@4

  v3 = a3;
  v4 = a2;
  v5 = 0;
  if ( !a2 || !a3 )
    return v5;
  LODWORD(v6) = OSCollectionIterator::withCollection(a3);
  if ( !v6 )
  {
    v9 = 0;
    return v9 & 1;
  }
  v29 = v6;
  LODWORD(v7) = (*(int (**)(void))(*(_QWORD *)v6 + 296LL))();
  v8 = v7;
  if ( !v7 )
  {
    v9 = 0;
    goto LABEL_22;
  }
  v27 = v3;
  v28 = *(_QWORD *)off_1000[0];
  v9 = 0;
  while ( 1 )
  {
    (*(void (__fastcall **)(__int64))(*(_QWORD *)v8 + 328LL))(v8);
    LODWORD(v10) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v4 + 680LL))(v4, v8);
    v11 = 0LL;
    if ( v10 )
    {
      LODWORD(v12) = OSMetaClassBase::safeMetaCast(v10, v28);
      v11 = v12;
    }
    LODWORD(v13) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v27 + 504LL))(v27, v8);
    LODWORD(v14) = OSMetaClassBase::safeMetaCast(v13, v28);
    v15 = v14;
    if ( v11 )
    {
      if ( v14 )
        break;
    }
    v4 = a2;
    v21 = *(int (__fastcall **)(_QWORD, _QWORD, _QWORD))(*(_QWORD *)a2 + 600LL);
    LODWORD(v22) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v27 + 504LL))(v27, v8);
    v20 = v21(a2, v8, v22);
LABEL_16:
    v9 = v20;
    if ( v20 )
    {
      LODWORD(v23) = (*(int (**)(void))(*(_QWORD *)v29 + 296LL))();
      v8 = v23;
      if ( v23 )
        continue;
    }
    goto LABEL_22;
  }
  LODWORD(v16) = OSDictionary::withDictionary(v11, 0LL);
  if ( v16 )
  {
    v17 = v16;
    v26 = v16;
    v18 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v11 + 312LL))(v11);
    v9 = (*(int (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 2136LL))(a1, v15, v17);
    v4 = a2;
    if ( !v9 )
      goto LABEL_22;
    if ( (*(int (__fastcall **)(__int64))(*(_QWORD *)v11 + 312LL))(v11) != v18 )
    {
      LODWORD(v19) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
      KernelDebugLogInternal(
        1LL,
        1431519814LL,
        "%s::MergeDictionaryIntoProvider  our provider's dictionary size changed (%d,%d)",
        v19);
    }
    v20 = (*(int (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a2 + 600LL))(a2, v8, v26);
    goto LABEL_16;
  }
  LODWORD(v24) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)a1 + 904LL))(a1, 0LL);
  KernelDebugLogInternal(
    1LL,
    1431519814LL,
    "%s::MergeDictionaryIntoProvider  could not copy our provider's dictionary",
    v24);
LABEL_22:
  (*(void (**)(void))(*(_QWORD *)v29 + 40LL))();
  return v9 & 1;
}
// 1000: using guessed type _QWORD off_1000[3];
// 89D0: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD);
// 8A28: using guessed type int __fastcall OSDictionary::withDictionary(_QWORD, _QWORD);
// 8BF8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// 8C28: using guessed type int __fastcall OSCollectionIterator::withCollection(_QWORD);

//----- (0000000000000CE8) ----------------------------------------------------
bool __fastcall IOUSBUserClientInit::MergeDictionaryIntoDictionary(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rbx@1
  bool result; // al@1
  __int64 v5; // rax@3
  __int64 v6; // rax@3
  __int64 v7; // rax@3
  __int64 v8; // r13@3
  __int64 v9; // r12@4
  __int64 v10; // rax@5
  __int64 v11; // r15@5
  __int64 v12; // rax@6
  __int64 v13; // rax@7
  __int64 v14; // rax@7
  char v15; // al@9
  int (__fastcall *v16)(_QWORD, _QWORD, _QWORD); // r15@10
  __int64 v17; // rax@10
  char v18; // r15@11
  __int64 v19; // rax@12
  __int64 v20; // rax@12
  __int64 v21; // [sp+8h] [bp-38h]@3
  __int64 v22; // [sp+10h] [bp-30h]@3

  v3 = a3;
  result = 0;
  if ( a2 && a3 )
  {
    LODWORD(v5) = OSCollectionIterator::withCollection(a2);
    v22 = v5;
    LODWORD(v6) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v5 + 296LL))(v5);
    v21 = *(_QWORD *)off_1008[0];
    LODWORD(v7) = OSMetaClassBase::safeMetaCast(v6, *(_QWORD *)off_1008[0]);
    v8 = v7;
    if ( v7 )
    {
      v9 = *(_QWORD *)off_1000[0];
      do
      {
        (*(void (__fastcall **)(__int64))(*(_QWORD *)v8 + 328LL))(v8);
        LODWORD(v10) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)v3 + 504LL))(v3, v8);
        v11 = 0LL;
        if ( v10 )
        {
          LODWORD(v12) = OSMetaClassBase::safeMetaCast(v10, v9);
          v11 = v12;
        }
        LODWORD(v13) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)a2 + 504LL))(a2, v8);
        LODWORD(v14) = OSMetaClassBase::safeMetaCast(v13, v9);
        if ( v11 && v14 )
        {
          v15 = (*(int (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 2136LL))(a1, v14, v11);
        }
        else
        {
          v16 = *(int (__fastcall **)(_QWORD, _QWORD, _QWORD))(*(_QWORD *)v3 + 448LL);
          LODWORD(v17) = (*(int (__fastcall **)(__int64, __int64))(*(_QWORD *)a2 + 504LL))(a2, v8);
          v15 = v16(v3, v8, v17);
        }
        v18 = v15;
        if ( !v15 )
          break;
        LODWORD(v19) = (*(int (**)(void))(*(_QWORD *)v22 + 296LL))();
        LODWORD(v20) = OSMetaClassBase::safeMetaCast(v19, v21);
        v8 = v20;
      }
      while ( v20 );
    }
    else
    {
      v18 = 0;
    }
    (*(void (**)(void))(*(_QWORD *)v22 + 40LL))();
    result = v18 != 0;
  }
  return result;
}
// 1000: using guessed type _QWORD off_1000[3];
// 1008: using guessed type _QWORD off_1008[2];
// 8BF8: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// 8C28: using guessed type int __fastcall OSCollectionIterator::withCollection(_QWORD);

//----- (0000000000000E40) ----------------------------------------------------
__int64 __fastcall IOUSBUserClientInit::MetaClass::~MetaClass(IOUSBUserClientInit::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000E50) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(&IOUSBUserClientInit::gMetaClass, "IOUSBUserClientInit", off_1010, 136LL);
  result = (__int64)off_18D0;
  IOUSBUserClientInit::gMetaClass = off_18D0;
  return result;
}
// 1010: using guessed type _QWORD off_1010;
// 18D0: using guessed type __int64 (__fastcall *off_18D0[2])(IOUSBUserClientInit::MetaClass *__hidden this);
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;
// 8A18: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000E90) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&IOUSBUserClientInit::gMetaClass);
}
// 1A70: using guessed type _QWORD IOUSBUserClientInit::gMetaClass;

//----- (0000000000000EA1) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 1A98: using guessed type int (*_realmain)(void);

//----- (0000000000000EBB) ----------------------------------------------------
__int64 *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 2;
}
// 19A8: using guessed type __int64 kmod_info;

//----- (0000000000000ECC) ----------------------------------------------------
__int64 *OSKextGetCurrentVersionString()
{
  return &kmod_info + 10;
}
// 19A8: using guessed type __int64 kmod_info;

//----- (0000000000000EDD) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *((_DWORD *)&kmod_info + 3);
}
// 19A8: using guessed type __int64 kmod_info;

//----- (0000000000000EED) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 1AA0: using guessed type int (*_antimain)(void);

// ALL OK, 23 function(s) have been successfully decompiled
