/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleUSBCompositePM::MetaClass::MetaClass(AppleUSBCompositePM::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBCompositePM::MetaClass::~MetaClass(AppleUSBCompositePM::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1);
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1);
__int64 __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *__hidden this); // idb
__int64 __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *__hidden this); // idb
void __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *this);
__int64 __fastcall AppleUSBCompositePM::getMetaClass(AppleUSBCompositePM *__hidden this); // idb
__int64 __fastcall AppleUSBCompositePM::MetaClass::MetaClass(AppleUSBCompositePM::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBCompositePM::MetaClass::alloc(AppleUSBCompositePM::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1);
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1);
__int64 __fastcall AppleUSBCompositePM::ConfigureDevicePowerManagement(AppleUSBCompositePM *this, uintptr_t arg2); // idb
__int64 __fastcall AppleUSBCompositePM::setPowerState(uintptr_t arg1, uintptr_t arg2, IOService *this); // idb
void __fastcall AppleUSBCompositePM::didTerminate(uintptr_t arg1, uintptr_t arg2);
__int64 __fastcall AppleUSBCompositePM::MetaClass::~MetaClass(AppleUSBCompositePM::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
__int64 __fastcall AppleUSBComposite::MetaClass::MetaClass(AppleUSBComposite::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::MetaClass::~MetaClass(AppleUSBComposite::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1);
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1);
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1);
__int64 __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *__hidden this); // idb
void __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *this);
__int64 __fastcall AppleUSBComposite::getMetaClass(AppleUSBComposite *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::MetaClass::MetaClass(AppleUSBComposite::MetaClass *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::MetaClass::alloc(AppleUSBComposite::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1);
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1);
__int64 __fastcall IOUSBCompositeDriver::MetaClass::MetaClass(IOUSBCompositeDriver::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::MetaClass::~MetaClass(IOUSBCompositeDriver::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1);
__int64 __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *__hidden this); // idb
void __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *this);
__int64 __fastcall IOUSBCompositeDriver::getMetaClass(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::MetaClass::MetaClass(IOUSBCompositeDriver::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::MetaClass::alloc(IOUSBCompositeDriver::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1);
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1);
unsigned __int8 __fastcall IOUSBCompositeDriver::start(uintptr_t arg1, uintptr_t arg2);
signed __int64 __fastcall IOUSBCompositeDriver::CompositeDriverInterestHandler(IOUSBCompositeDriver *this, void *a2, void *a3, __int64 a4, IOService *a5, void *a6);
char __fastcall IOUSBCompositeDriver::init(__int64 a1);
int __fastcall IOUSBCompositeDriver::free(IOUSBCompositeDriver *this);
int __fastcall IOUSBCompositeDriver::message(IOUSBCompositeDriver *this, __int64 a2, IOService *a3, void *a4);
int __fastcall IOUSBCompositeDriver::willTerminate(IOUSBCompositeDriver *this, IOService *a2, unsigned int a3);
int __fastcall IOUSBCompositeDriver::didTerminate(IOUSBCompositeDriver *this, IOService *a2, unsigned int a3, bool *a4);
bool __fastcall IOUSBCompositeDriver::ConfigureDevice(uintptr_t arg1);
// uintptr_t __usercall IOUSBCompositeDriver::GetConfigDescriptor@<rax>(uintptr_t arg1@<rdi>, __int64 a2@<rax>, unsigned __int8 a3@<sil>);
__int64 __fastcall IOUSBCompositeDriver::ReConfigureDevice(IOUSBCompositeDriver *__hidden this); // idb
int __fastcall IOUSBCompositeDriver::SetConfiguration(IOUSBCompositeDriver *this, unsigned __int8 a2, unsigned __int8 a3);
__int64 __fastcall IOUSBCompositeDriver::ConfigureDevicePowerManagement(IOUSBCompositeDriver *this, IOService *a2);
// __int64 __usercall IOUSBCompositeDriver::FindPreferredConfiguration@<rax>(uintptr_t arg1@<rdi>, unsigned __int8 *a2@<rsi>, __int64 a3@<rax>);
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPreferredConfiguration(uintptr_t arg1, unsigned __int8 *, bool *); // idb
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPreferredInterface(uintptr_t arg1, unsigned __int8 *, bool *); // idb
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPowerRequirements(uintptr_t arg1, unsigned __int8 *, bool *); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver2(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver3(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver4(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver5(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver6(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver7(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver8(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver9(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver10(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver11(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver12(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver13(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver14(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver15(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver16(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver17(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver18(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver19(IOUSBCompositeDriver *__hidden this); // idb
__int64 __fastcall AppleUSBComposite::MetaClass::~MetaClass(AppleUSBComposite::MetaClass *__hidden this); // idb
__int64 __fastcall IOUSBCompositeDriver::MetaClass::~MetaClass(IOUSBCompositeDriver::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a_0();
__int64 `global destructor keyed to'_a_0();
int _start();
__int64 *OSKextGetCurrentIdentifier();
__int64 *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall IOFree(_QWORD, _QWORD); weak
// int __fastcall IOMalloc(_QWORD); weak
// int __fastcall IOSleep(_QWORD, _QWORD); weak
// int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD IOUSBDevice::GetLocationID(IOUSBDevice *__hidden this); idb
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// _QWORD IOService::makeUsable(IOService *__hidden this); idb
// _QWORD IOService::getPowerState(IOService *__hidden this); idb
// _QWORD __cdecl IOService::changePowerStateTo(IOService *__hidden this, unsigned __int64); idb
// _QWORD __cdecl IOService::changePowerStateToPriv(IOService *__hidden this, unsigned __int64); idb
// int __cdecl IOService::IOService(_QWORD); weak
// _QWORD __cdecl IOService::~IOService(IOService *__hidden this); idb
// _QWORD __cdecl OSMetaClass::reservedCalled(OSMetaClass *__hidden this, int); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb
// _QWORD IOService::isInactive(IOService *__hidden this); idb
// void __cdecl bzero(void *, size_t);
// void __cdecl kernel_debug(uint32_t debugid, uintptr_t arg1, uintptr_t arg2, uintptr_t arg3, uintptr_t arg4, uintptr_t arg5);

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_68 =
{
  {
    '_',
    '_',
    't',
    'e',
    'x',
    't',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  2880uLL,
  8723uLL,
  2880u,
  4u,
  0u,
  0u,
  2147484672u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_3000[7] = { 62648LL, 63392LL, 64968LL, 64984LL, 64992LL, 65000LL, 65008LL }; // weak
_QWORD off_3008[6] = { 63392LL, 64968LL, 64984LL, 64992LL, 65000LL, 65008LL }; // weak
__int64 off_3010[5] = { 64968LL, 64984LL, 64992LL, 65000LL, 65008LL }; // weak
__int64 off_3018[4] = { 64984LL, 64992LL, 65000LL, 65008LL }; // weak
__int64 off_3020[3] = { 64992LL, 65000LL, 65008LL }; // weak
__int64 off_3028[2] = { 65000LL, 65008LL }; // weak
__int64 off_3030 = 65008LL; // weak
__int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this) =
{
  &AppleUSBCompositePM::~AppleUSBCompositePM,
  &AppleUSBCompositePM::~AppleUSBCompositePM
}; // weak
__int64 (__fastcall *off_39A0[2])(AppleUSBCompositePM::MetaClass *__hidden this) =
{
  &AppleUSBCompositePM::MetaClass::~MetaClass,
  &AppleUSBCompositePM::MetaClass::~MetaClass
}; // weak
__int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this) =
{
  &AppleUSBComposite::~AppleUSBComposite,
  &AppleUSBComposite::~AppleUSBComposite
}; // weak
__int64 (__fastcall *off_43C0[2])(AppleUSBComposite::MetaClass *__hidden this) =
{
  &AppleUSBComposite::MetaClass::~MetaClass,
  &AppleUSBComposite::MetaClass::~MetaClass
}; // weak
__int64 `vtable for'IOUSBCompositeDriver[2] = { 0LL, 0LL }; // weak
__int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this) =
{
  &IOUSBCompositeDriver::~IOUSBCompositeDriver,
  &IOUSBCompositeDriver::~IOUSBCompositeDriver
}; // weak
__int64 (__fastcall *off_4DE0[2])(IOUSBCompositeDriver::MetaClass *__hidden this) =
{
  &IOUSBCompositeDriver::MetaClass::~MetaClass,
  &IOUSBCompositeDriver::MetaClass::~MetaClass
}; // weak
_QWORD ourPowerStates = 1LL; // weak
__int64 kmod_info = 0LL; // weak
_QWORD AppleUSBCompositePM::gMetaClass; // weak
_QWORD AppleUSBComposite::gMetaClass; // weak
_QWORD IOUSBCompositeDriver::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak


//----- (0000000000000B40) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::MetaClass::MetaClass(AppleUSBCompositePM::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBCompositePM", &IOUSBCompositeDriver::gMetaClass, 168LL);
  result = (__int64)off_39A0;
  *(_QWORD *)this = off_39A0;
  return result;
}
// 39A0: using guessed type __int64 (__fastcall *off_39A0[2])(AppleUSBCompositePM::MetaClass *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000B72) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::MetaClass::~MetaClass(AppleUSBCompositePM::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000B7C) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1);
  result = (__int64)off_3080;
  *(_QWORD *)a1 = off_3080;
  return result;
}
// 3080: using guessed type __int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this);

//----- (0000000000000B9C) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1)
{
  __int64 result; // rax@1

  IOUSBCompositeDriver::IOUSBCompositeDriver(a1);
  result = (__int64)off_3080;
  *(_QWORD *)a1 = off_3080;
  return result;
}
// 3080: using guessed type __int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this);

//----- (0000000000000BBC) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (0000000000000BC6) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *this)
{
  return IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
}

//----- (0000000000000BD0) ----------------------------------------------------
void __fastcall AppleUSBCompositePM::~AppleUSBCompositePM(AppleUSBCompositePM *this)
{
  IOUSBCompositeDriver::~IOUSBCompositeDriver(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000000BF2) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::getMetaClass(AppleUSBCompositePM *this)
{
  return (__int64)&AppleUSBCompositePM::gMetaClass;
}
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;

//----- (0000000000000C00) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::MetaClass::MetaClass(AppleUSBCompositePM::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBCompositePM", &IOUSBCompositeDriver::gMetaClass, 168LL);
  result = (__int64)off_39A0;
  *(_QWORD *)this = off_39A0;
  return result;
}
// 39A0: using guessed type __int64 (__fastcall *off_39A0[2])(AppleUSBCompositePM::MetaClass *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000C32) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::MetaClass::alloc(AppleUSBCompositePM::MetaClass *this, unsigned __int64 a2)
{
  __int64 v2; // rbx@1

  v2 = OSObject::operator new((OSObject *)&stru_68.flags, a2);
  IOUSBCompositeDriver::IOUSBCompositeDriver(v2);
  *(_QWORD *)v2 = off_3080;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCompositePM::gMetaClass);
  return v2;
}
// 68: using guessed type section_64 stru_68;
// 3080: using guessed type __int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this);
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;

//----- (0000000000000C72) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1);
  *(_QWORD *)a1 = off_3080;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCompositePM::gMetaClass);
}
// 3080: using guessed type __int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this);
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;

//----- (0000000000000CA2) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::AppleUSBCompositePM(__int64 a1)
{
  IOUSBCompositeDriver::IOUSBCompositeDriver(a1);
  *(_QWORD *)a1 = off_3080;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBCompositePM::gMetaClass);
}
// 3080: using guessed type __int64 (__fastcall *off_3080[2])(AppleUSBCompositePM *__hidden this);
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;

//----- (0000000000000CD2) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::ConfigureDevicePowerManagement(AppleUSBCompositePM *this, uintptr_t arg2)
{
  uintptr_t v2; // r14@1
  __int64 v3; // r15@1
  int v4; // er14@4

  v2 = arg2;
  v3 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
  {
    arg2 = (uintptr_t)this;
    kernel_debug(0x52D9051u, (uintptr_t)this, v2, 0LL, 0LL, 0LL);
  }
  (*(void (__fastcall **)(AppleUSBCompositePM *, uintptr_t))(*(_QWORD *)this + 1936LL))(this, arg2);
  (*(void (__fastcall **)(uintptr_t, AppleUSBCompositePM *))(*(_QWORD *)v2 + 1952LL))(v2, this);
  IOService::makeUsable(this);
  IOService::changePowerStateTo(this, 2uLL);
  IOService::changePowerStateToPriv(this, 0LL);
  v4 = (*(int (__fastcall **)(AppleUSBCompositePM *, AppleUSBCompositePM *, _QWORD *, signed __int64))(*(_QWORD *)this + 1960LL))(
         this,
         this,
         &ourPowerStates,
         5LL);
  if ( *(_BYTE *)v3 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9052u, (uintptr_t)this, v4, 0LL, 0LL, 0LL);
  return (unsigned int)v4;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;
// 4EC0: using guessed type _QWORD ourPowerStates;

//----- (0000000000000DAA) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::setPowerState(uintptr_t arg1, uintptr_t arg2, IOService *this)
{
  IOService *v3; // rbx@1
  uintptr_t v4; // r14@1
  __int64 v5; // r12@1
  unsigned int v6; // eax@9
  __int64 v7; // rdi@11
  __int64 v8; // rax@11
  signed __int64 v9; // rsi@11
  unsigned int v10; // eax@15

  v3 = this;
  v4 = arg1;
  v5 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9055u, arg1, arg2, (uintptr_t)this, *(_QWORD *)(arg1 + 136), 0LL);
  if ( (IOService *)arg1 == v3 && !(unsigned __int8)IOService::isInactive(v3) )
  {
    if ( arg2 <= 3 && (unsigned int)IOService::getPowerState(v3) == 4 )
    {
      if ( *(_BYTE *)v5 & 2 )
      {
        v6 = IOService::getPowerState(v3);
        if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
          kernel_debug(0x52D9054u, arg1, arg2, v6, 0LL, 0LL);
      }
      v7 = *(_QWORD *)(arg1 + 136);
      v8 = *(_QWORD *)v7;
      v9 = 1LL;
LABEL_18:
      (*(void (__fastcall **)(__int64, signed __int64))(v8 + 2440))(v7, v9);
      goto LABEL_19;
    }
    if ( arg2 == 4 && (unsigned int)IOService::getPowerState(v3) <= 3 )
    {
      if ( *(_BYTE *)v5 & 2 )
      {
        v10 = IOService::getPowerState(v3);
        if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
          kernel_debug(0x52D9054u, arg1, 4uLL, v10, 1uLL, 0LL);
      }
      v7 = *(_QWORD *)(arg1 + 136);
      v8 = *(_QWORD *)v7;
      v9 = 0LL;
      goto LABEL_18;
    }
  }
LABEL_19:
  if ( *(_BYTE *)v5 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9056u, v4, 0LL, 0LL, 0LL, 0LL);
  return 0LL;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;

//----- (0000000000000F04) ----------------------------------------------------
void __fastcall AppleUSBCompositePM::didTerminate(uintptr_t arg1, uintptr_t arg2)
{
  uintptr_t v2; // r12@1
  __int64 v3; // r13@1

  v2 = arg2;
  v3 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
  {
    arg2 = arg1;
    kernel_debug(0x52D9059u, arg1, v2, *(_QWORD *)(arg1 + 136), 0LL, 0LL);
  }
  (*(void (__fastcall **)(uintptr_t, uintptr_t))(*(_QWORD *)arg1 + 1944LL))(arg1, arg2);
  if ( *(_BYTE *)v3 & 2 )
  {
    if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      kernel_debug(0x52D905Au, arg1, 0LL, 0LL, 0LL, 0LL);
  }
  JUMPOUT(__CS__, `vtable for'IOUSBCompositeDriver[131]);
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;
// 44B0: using guessed type __int64 `vtable for'IOUSBCompositeDriver[2];

//----- (0000000000000FB8) ----------------------------------------------------
__int64 __fastcall AppleUSBCompositePM::MetaClass::~MetaClass(AppleUSBCompositePM::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000FD0) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(
    &AppleUSBCompositePM::gMetaClass,
    "AppleUSBCompositePM",
    &IOUSBCompositeDriver::gMetaClass,
    168LL);
  result = (__int64)off_39A0;
  AppleUSBCompositePM::gMetaClass = off_39A0;
  return result;
}
// 39A0: using guessed type __int64 (__fastcall *off_39A0[2])(AppleUSBCompositePM::MetaClass *__hidden this);
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001010) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBCompositePM::gMetaClass);
}
// 5168: using guessed type _QWORD AppleUSBCompositePM::gMetaClass;

//----- (0000000000001030) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::MetaClass::MetaClass(AppleUSBComposite::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBComposite", &IOUSBCompositeDriver::gMetaClass, 168LL);
  result = (__int64)off_43C0;
  *(_QWORD *)this = off_43C0;
  return result;
}
// 43C0: using guessed type __int64 (__fastcall *off_43C0[2])(AppleUSBComposite::MetaClass *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001062) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::MetaClass::~MetaClass(AppleUSBComposite::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (000000000000106C) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_3AA0;
  *(_QWORD *)a1 = off_3AA0;
  return result;
}
// 3AA0: using guessed type __int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this);
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (000000000000108C) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_44C0;
  *(_QWORD *)a1 = off_44C0;
  return result;
}
// 44C0: using guessed type __int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this);
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (00000000000010AC) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_3AA0;
  *(_QWORD *)a1 = off_3AA0;
  return result;
}
// 3AA0: using guessed type __int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this);
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (00000000000010CC) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *this)
{
  return IOService::~IOService(this);
}

//----- (00000000000010D6) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *this)
{
  return IOService::~IOService(this);
}

//----- (00000000000010E0) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *this)
{
  return IOService::~IOService(this);
}

//----- (00000000000010EA) ----------------------------------------------------
void __fastcall AppleUSBComposite::~AppleUSBComposite(AppleUSBComposite *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (000000000000110C) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::getMetaClass(AppleUSBComposite *this)
{
  return (__int64)&AppleUSBComposite::gMetaClass;
}
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;

//----- (000000000000111A) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::MetaClass::MetaClass(AppleUSBComposite::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleUSBComposite", &IOUSBCompositeDriver::gMetaClass, 168LL);
  result = (__int64)off_43C0;
  *(_QWORD *)this = off_43C0;
  return result;
}
// 43C0: using guessed type __int64 (__fastcall *off_43C0[2])(AppleUSBComposite::MetaClass *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000114C) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::MetaClass::alloc(AppleUSBComposite::MetaClass *this, unsigned __int64 a2)
{
  __int64 v2; // rbx@1

  v2 = OSObject::operator new((OSObject *)&stru_68.flags, a2);
  IOService::IOService(v2);
  *(_QWORD *)v2 = off_3AA0;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBComposite::gMetaClass);
  return v2;
}
// 68: using guessed type section_64;
// 3AA0: using guessed type __int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this);
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (000000000000118C) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_3AA0;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBComposite::gMetaClass);
}
// 3AA0: using guessed type __int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this);
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (00000000000011BC) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::AppleUSBComposite(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_3AA0;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleUSBComposite::gMetaClass);
}
// 3AA0: using guessed type __int64 (__fastcall *off_3AA0[2])(AppleUSBComposite *__hidden this);
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (00000000000011EC) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::MetaClass::MetaClass(IOUSBCompositeDriver::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "IOUSBCompositeDriver", off_3008[0], 168LL);
  result = (__int64)off_4DE0;
  *(_QWORD *)this = off_4DE0;
  return result;
}
// 3008: using guessed type _QWORD off_3008[6];
// 4DE0: using guessed type __int64 (__fastcall *off_4DE0[2])(IOUSBCompositeDriver::MetaClass *__hidden this);
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (000000000000121E) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::MetaClass::~MetaClass(IOUSBCompositeDriver::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000001228) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1)
{
  __int64 result; // rax@1

  IOService::IOService(a1);
  result = (__int64)off_44C0;
  *(_QWORD *)a1 = off_44C0;
  return result;
}
// 44C0: using guessed type __int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this);
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000001248) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *this)
{
  return IOService::~IOService(this);
}

//----- (0000000000001252) ----------------------------------------------------
void __fastcall IOUSBCompositeDriver::~IOUSBCompositeDriver(IOUSBCompositeDriver *this)
{
  IOService::~IOService(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000001274) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::getMetaClass(IOUSBCompositeDriver *this)
{
  return (__int64)&IOUSBCompositeDriver::gMetaClass;
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000001282) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::MetaClass::MetaClass(IOUSBCompositeDriver::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "IOUSBCompositeDriver", off_3008[0], 168LL);
  result = (__int64)off_4DE0;
  *(_QWORD *)this = off_4DE0;
  return result;
}
// 3008: using guessed type _QWORD off_3008[6];
// 4DE0: using guessed type __int64 (__fastcall *off_4DE0[2])(IOUSBCompositeDriver::MetaClass *__hidden this);
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000012B4) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::MetaClass::alloc(IOUSBCompositeDriver::MetaClass *this, unsigned __int64 a2)
{
  __int64 v2; // rbx@1

  v2 = OSObject::operator new((OSObject *)&stru_68.flags, a2);
  IOService::IOService(v2);
  *(_QWORD *)v2 = off_44C0;
  OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass);
  return v2;
}
// 68: using guessed type section_64 stru_68;
// 44C0: using guessed type __int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (00000000000012F4) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_44C0;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass);
}
// 44C0: using guessed type __int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000001324) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::IOUSBCompositeDriver(__int64 a1)
{
  IOService::IOService(a1);
  *(_QWORD *)a1 = off_44C0;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass);
}
// 44C0: using guessed type __int64 (__fastcall *off_44C0[2])(IOUSBCompositeDriver *__hidden this);
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// FBB0: using guessed type int __cdecl IOService::IOService(_QWORD);

//----- (0000000000001354) ----------------------------------------------------
unsigned __int8 __fastcall IOUSBCompositeDriver::start(uintptr_t arg1, uintptr_t arg2)
{
  uintptr_t v2; // rbx@1
  __int64 v3; // r12@1
  __int64 v4; // rax@5
  unsigned __int8 v5; // r14@9
  uintptr_t v6; // r8@9
  unsigned __int16 v7; // bx@19
  unsigned int v8; // eax@19
  __int64 v10; // rax@23

  v2 = arg2;
  v3 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D900Du, arg1, arg2, 0LL, 0LL, 0LL);
  if ( !(unsigned __int8)(*(int (__fastcall **)(uintptr_t, uintptr_t))(off_3010[0] + 1488))(arg1, arg2) )
  {
    if ( *(_BYTE *)v3 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    {
      v5 = 0;
      v6 = 0LL;
      goto LABEL_16;
    }
LABEL_17:
    v5 = 0;
    goto LABEL_18;
  }
  arg2 = *(_QWORD *)off_3000[0];
  LODWORD(v4) = OSMetaClassBase::safeMetaCast(v2, *(_QWORD *)off_3000[0]);
  *(_QWORD *)(arg1 + 136) = v4;
  if ( !v4 )
  {
    if ( *(_BYTE *)v3 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    {
      v5 = 0;
      v6 = 1LL;
      goto LABEL_16;
    }
    goto LABEL_17;
  }
  *(_BYTE *)(arg1 + 152) = 0;
  *(_QWORD *)(arg1 + 144) = 0LL;
  arg2 = v2;
  if ( (*(int (__fastcall **)(uintptr_t, uintptr_t))(*(_QWORD *)arg1 + 2152LL))(arg1, v2) )
  {
    if ( *(_BYTE *)v3 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    {
      v5 = 0;
      v6 = 2LL;
LABEL_16:
      arg2 = arg1;
      kernel_debug(0x52D900Cu, arg1, 0LL, 0LL, v6, 0LL);
      goto LABEL_18;
    }
    goto LABEL_17;
  }
  v5 = (*(int (__fastcall **)(uintptr_t))(*(_QWORD *)arg1 + 2128LL))(arg1);
  if ( v5 )
  {
    arg2 = *(_QWORD *)off_3018[0];
    LODWORD(v10) = (*(int (__fastcall **)(_QWORD, _QWORD, signed __int64 (__fastcall *)(IOUSBCompositeDriver *, void *, void *, __int64, IOService *, void *), uintptr_t, _QWORD))(**(_QWORD **)(arg1 + 136) + 1864LL))(
                     *(_QWORD *)(arg1 + 136),
                     *(_QWORD *)off_3018[0],
                     IOUSBCompositeDriver::CompositeDriverInterestHandler,
                     arg1,
                     0LL);
    *(_QWORD *)(arg1 + 144) = v10;
  }
LABEL_18:
  if ( *(_BYTE *)v3 & 2 )
  {
    v7 = (*(int (__fastcall **)(_QWORD, uintptr_t))(**(_QWORD **)(arg1 + 136) + 2248LL))(*(_QWORD *)(arg1 + 136), arg2);
    v8 = IOUSBDevice::GetLocationID(*(IOUSBDevice **)(arg1 + 136));
    if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      kernel_debug(0x52D900Eu, arg1, v5, v7, v8, 0LL);
  }
  return v5;
}
// 3000: using guessed type _QWORD off_3000[7];
// 3010: using guessed type __int64 off_3010[5];
// 3018: using guessed type __int64 off_3018[4];
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;
// F6D0: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);

//----- (0000000000001524) ----------------------------------------------------
signed __int64 __fastcall IOUSBCompositeDriver::CompositeDriverInterestHandler(IOUSBCompositeDriver *this, void *a2, void *a3, __int64 a4, IOService *a5, void *a6)
{
  signed __int64 result; // rax@1

  result = 3758097084LL;
  if ( this )
  {
    result = 0LL;
    if ( (_DWORD)a3 == -536870640 )
      *((_BYTE *)this + 152) = 0;
  }
  return result;
}

//----- (0000000000001546) ----------------------------------------------------
char __fastcall IOUSBCompositeDriver::init(__int64 a1)
{
  char v1; // r14@2
  void *v2; // rax@3

  if ( !(unsigned __int8)(*(int (**)(void))(off_3010[0] + 600))() )
    goto LABEL_5;
  v1 = 1;
  if ( !*(_QWORD *)(a1 + 160) )
  {
    LODWORD(v2) = IOMalloc(8LL);
    *(_QWORD *)(a1 + 160) = v2;
    if ( v2 )
    {
      bzero(v2, 8uLL);
      return v1;
    }
LABEL_5:
    v1 = 0;
  }
  return v1;
}
// 3010: using guessed type __int64 off_3010[5];
// F498: using guessed type int __fastcall IOMalloc(_QWORD);

//----- (000000000000159E) ----------------------------------------------------
int __fastcall IOUSBCompositeDriver::free(IOUSBCompositeDriver *this)
{
  IOUSBCompositeDriver *v1; // rbx@1
  __int64 v2; // rdi@1

  v1 = this;
  v2 = *((_QWORD *)this + 20);
  if ( v2 )
  {
    IOFree(v2, 8LL);
    *((_QWORD *)v1 + 20) = 0LL;
  }
  return (*(int (__fastcall **)(IOUSBCompositeDriver *))(off_3010[0] + 160))(v1);
}
// 3010: using guessed type __int64 off_3010[5];
// F490: using guessed type int __fastcall IOFree(_QWORD, _QWORD);

//----- (00000000000015DE) ----------------------------------------------------
int __fastcall IOUSBCompositeDriver::message(IOUSBCompositeDriver *this, __int64 a2, IOService *a3, void *a4)
{
  IOUSBCompositeDriver *v4; // r12@1
  int v5; // er14@1
  __int64 v6; // rdi@2
  signed int v7; // er15@2
  __int64 v8; // rax@6

  v4 = this;
  v5 = (*(int (__fastcall **)(IOUSBCompositeDriver *, __int64, IOService *, void *))(off_3010[0] + 1856))(
         this,
         a2,
         a3,
         a4);
  if ( (_DWORD)a2 == -536870656 )
  {
    v6 = *((_QWORD *)this + 17);
    v7 = -536870195;
    if ( !v6
      || !(unsigned __int8)(*(int (__fastcall **)(__int64, IOUSBCompositeDriver *))(*(_QWORD *)v6 + 1504LL))(v6, v4) )
      return v7;
    *((_BYTE *)v4 + 152) = 1;
    (*(void (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD))(**((_QWORD **)v4 + 17) + 1496LL))(
      *((_QWORD *)v4 + 17),
      v4,
      0LL);
    return v5;
  }
  if ( (_DWORD)a2 != -536854518 )
    return v5;
  v8 = *((_QWORD *)this + 20);
  if ( *(_BYTE *)(v8 + 2) )
  {
    *(_BYTE *)(v8 + 2) = 0;
    return v5;
  }
  return (*(int (**)(void))(*(_QWORD *)this + 2136LL))();
}
// 3010: using guessed type __int64 off_3010[5];

//----- (0000000000001688) ----------------------------------------------------
int __fastcall IOUSBCompositeDriver::willTerminate(IOUSBCompositeDriver *this, IOService *a2, unsigned int a3)
{
  unsigned int v3; // er14@1
  IOUSBCompositeDriver *v4; // rbx@1
  __int64 v5; // rdi@1

  v3 = a3;
  v4 = this;
  v5 = *((_QWORD *)this + 18);
  if ( v5 )
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v5 + 280LL))(v5);
  return (*(int (__fastcall **)(IOUSBCompositeDriver *, IOService *, _QWORD))(off_3010[0] + 1040))(v4, a2, v3);
}
// 3010: using guessed type __int64 off_3010[5];

//----- (00000000000016D0) ----------------------------------------------------
int __fastcall IOUSBCompositeDriver::didTerminate(IOUSBCompositeDriver *this, IOService *a2, unsigned int a3, bool *a4)
{
  bool *v4; // r14@1
  unsigned int v5; // er15@1

  v4 = a4;
  v5 = a3;
  if ( (unsigned __int8)(*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *))(**((_QWORD **)this + 17) + 1504LL))(
                          *((_QWORD *)this + 17),
                          this) )
    (*(void (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD))(**((_QWORD **)this + 17) + 1496LL))(
      *((_QWORD *)this + 17),
      this,
      0LL);
  return (*(int (__fastcall **)(IOUSBCompositeDriver *, IOService *, _QWORD, bool *))(off_3010[0] + 1048))(
           this,
           a2,
           v5,
           v4);
}
// 3010: using guessed type __int64 off_3010[5];

//----- (0000000000001734) ----------------------------------------------------
bool __fastcall IOUSBCompositeDriver::ConfigureDevice(uintptr_t arg1)
{
  uintptr_t v1; // r14@1
  __int64 v2; // r12@1
  uintptr_t v3; // rbx@2
  unsigned int v4; // eax@2
  __int64 v5; // rax@4
  int v6; // ebx@9
  uintptr_t v7; // r15@10
  unsigned __int8 v8; // al@12
  char v9; // cl@12
  __int64 v10; // rax@15
  __int64 v11; // r15@15
  __int64 v12; // rax@15
  __int64 v13; // rdi@15
  __int64 v14; // rax@15
  __int64 v15; // rax@16
  __int64 v16; // r15@16
  __int64 v17; // rax@16
  __int64 v18; // r9@16
  __int64 v19; // rax@17
  __int64 v20; // r15@17
  __int64 v21; // rax@17
  __int64 v22; // r9@17
  char v23; // al@19
  uintptr_t v24; // rsi@21
  int v25; // eax@21
  int v26; // eax@25
  __int64 v27; // rax@29
  __int64 v28; // rbx@29
  __int64 v29; // rax@30
  __int64 v30; // rax@30
  __int64 v31; // rax@30
  __int64 v32; // rax@31
  int v33; // eax@32
  unsigned __int8 v35; // [sp+Fh] [bp-21h]@1

  v1 = arg1;
  v35 = 0;
  v2 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 )
  {
    v3 = *(_QWORD *)(arg1 + 136);
    v4 = IOUSBDevice::GetLocationID(*(IOUSBDevice **)(arg1 + 136));
    if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      kernel_debug(0x52D9005u, arg1, v3, v4, 0LL, 0LL);
  }
  LODWORD(v5) = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2312LL))();
  if ( (_BYTE)v5 )
  {
    if ( (unsigned __int8)v5 < 2u )
      goto LABEL_44;
    if ( *(_BYTE *)v2 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      kernel_debug(0x52D9004u, arg1, (unsigned __int8)v5, 0LL, 0LL, 0LL);
    LODWORD(v5) = (*(int (__fastcall **)(uintptr_t, char *))(*(_QWORD *)arg1 + 2160LL))(arg1, &v35);
    v6 = v5;
    if ( !(_DWORD)v5 )
    {
LABEL_44:
      v7 = IOUSBCompositeDriver::GetConfigDescriptor(arg1, v5, v35);
      v6 = -536870208;
      if ( v7 )
      {
        if ( (unsigned __int8)(*(int (__fastcall **)(_QWORD, uintptr_t, _QWORD, _QWORD))(**(_QWORD **)(arg1 + 136)
                                                                                       + 1488LL))(
                                *(_QWORD *)(arg1 + 136),
                                arg1,
                                0LL,
                                0LL) )
        {
          v8 = *(_BYTE *)(v7 + 5);
          *(_BYTE *)(arg1 + 153) = v8;
          v9 = *(_BYTE *)(v7 + 7);
          *(_BYTE *)(arg1 + 154) = v9;
          if ( v9 & 0x20 )
            **(_BYTE **)(arg1 + 160) = 1;
          v6 = (*(int (__fastcall **)(uintptr_t, _QWORD, signed __int64))(*(_QWORD *)arg1 + 2144LL))(arg1, v8, 1LL);
          if ( v6 )
          {
            LODWORD(v10) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)arg1 + 904LL))(arg1, 0LL);
            v11 = v10;
            LODWORD(v12) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 904LL))(
                             *(_QWORD *)(arg1 + 136),
                             0LL);
            KernelDebugLogInternal(
              1LL,
              1431519814LL,
              "%s(%s)::ConfigureDevice SetConfiguration (%d) returned 0x%x",
              v11,
              v12,
              *(_BYTE *)(arg1 + 153));
            v13 = *(_QWORD *)(arg1 + 136);
            v14 = *(_QWORD *)v13;
          }
          else
          {
            if ( !*(_BYTE *)(*(_QWORD *)(arg1 + 160) + 1LL) )
            {
              v23 = *(_BYTE *)(v7 + 7);
              *(_BYTE *)(arg1 + 154) = v23;
              if ( v23 & 0x20 )
              {
                if ( (unsigned __int8)(*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2256LL))() != 3 )
                {
                  v24 = 1LL;
                  v25 = (*(int (__fastcall **)(_QWORD, signed __int64))(**(_QWORD **)(arg1 + 136) + 2144LL))(
                          *(_QWORD *)(arg1 + 136),
                          1LL);
                  if ( v25 )
                  {
                    if ( *(_BYTE *)v2 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
                    {
                      v24 = arg1;
                      kernel_debug(0x52D9004u, arg1, v25, 0LL, 1uLL, 0LL);
                    }
                    IOSleep(300LL, v24);
                    v26 = (*(int (__fastcall **)(_QWORD, signed __int64))(**(_QWORD **)(arg1 + 136) + 2144LL))(
                            *(_QWORD *)(arg1 + 136),
                            1LL);
                    if ( v26 && *(_BYTE *)v2 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
                      kernel_debug(0x52D9004u, arg1, v26, 0LL, 2uLL, 0LL);
                  }
                }
              }
            }
            LODWORD(v27) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 696LL))(
                             *(_QWORD *)(arg1 + 136),
                             "ExpressCardCantWake");
            v28 = *(_QWORD *)off_3028[0];
            if ( v27 == **(_QWORD **)off_3028[0] )
            {
              LODWORD(v29) = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2264LL))();
              (*(void (__fastcall **)(__int64))(*(_QWORD *)v29 + 32LL))(v29);
              LODWORD(v30) = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2264LL))();
              (*(void (__fastcall **)(__int64, signed __int64, uintptr_t, _QWORD))(*(_QWORD *)v30 + 1840LL))(
                v30,
                3758112784LL,
                arg1,
                *(_QWORD *)(arg1 + 136));
              LODWORD(v31) = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2264LL))();
              (*(void (__fastcall **)(__int64))(*(_QWORD *)v31 + 40LL))(v31);
            }
            LODWORD(v32) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 696LL))(
                             *(_QWORD *)(arg1 + 136),
                             "kSuspendPort");
            if ( v32 == *(_QWORD *)v28 )
            {
              v33 = (*(int (__fastcall **)(_QWORD, signed __int64))(**(_QWORD **)(arg1 + 136) + 2440LL))(
                      *(_QWORD *)(arg1 + 136),
                      1LL);
              if ( v33 )
              {
                if ( *(_BYTE *)v2 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
                  kernel_debug(0x52D9004u, arg1, v33, 0LL, 3uLL, 0LL);
              }
            }
            *(_BYTE *)(arg1 + 152) = 1;
            v13 = *(_QWORD *)(arg1 + 136);
            v14 = *(_QWORD *)v13;
            v6 = 0;
          }
          (*(void (__fastcall **)(__int64, uintptr_t, _QWORD))(v14 + 1496))(v13, v1, 0LL);
        }
        else
        {
          LODWORD(v19) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)arg1 + 904LL))(arg1, 0LL);
          v20 = v19;
          LODWORD(v21) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 904LL))(
                           *(_QWORD *)(arg1 + 136),
                           0LL);
          KernelDebugLogInternal(1LL, 1431519814LL, "%s::ConfigureDevice Could not open device (%s)", v20, v21, v22);
          v6 = -536870203;
        }
      }
    }
  }
  else
  {
    LODWORD(v15) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)arg1 + 904LL))(arg1, 0LL);
    v16 = v15;
    LODWORD(v17) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 904LL))(
                     *(_QWORD *)(arg1 + 136),
                     0LL);
    KernelDebugLogInternal(1LL, 1431519814LL, "%s(%s)::ConfigureDevice Could not get any configurations", v16, v17, v18);
    v6 = -536854442;
  }
  if ( *(_BYTE *)v2 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9006u, v1, *(_QWORD *)(v1 + 136), v6, v6 == 0, 0LL);
  return v6 == 0;
}
// 3020: using guessed type __int64 off_3020[3];
// 3028: using guessed type __int64 off_3028[2];
// 3030: using guessed type __int64 off_3030;
// F4A0: using guessed type int __fastcall IOSleep(_QWORD, _QWORD);
// F4A8: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001BA0) ----------------------------------------------------
uintptr_t __usercall IOUSBCompositeDriver::GetConfigDescriptor@<rax>(uintptr_t arg1@<rdi>, __int64 a2@<rax>, unsigned __int8 a3@<sil>)
{
  uintptr_t v3; // r15@1
  __int64 v4; // r13@1
  __int64 v5; // rdi@4
  int v6; // er12@4
  uintptr_t v7; // rbx@4
  char v8; // r12@5
  unsigned int v9; // er14@5
  uintptr_t v10; // rsi@5
  uintptr_t v11; // rax@5
  uintptr_t v12; // rax@9
  __int64 v13; // rax@13
  __int64 v14; // r12@13
  __int64 v15; // rax@13
  uintptr_t v16; // rax@19
  __int64 v18; // rax@28
  __int64 v19; // r12@28
  __int64 v20; // rax@28
  __int64 v21; // [sp+0h] [bp-30h]@1

  v21 = a2;
  v3 = arg1;
  v4 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9011u, arg1, *(_QWORD *)(arg1 + 136), 0LL, 0LL, 0LL);
  v5 = *(_QWORD *)(arg1 + 136);
  v6 = -536870208;
  v7 = 0LL;
  if ( v5 )
  {
    HIDWORD(v21) = 0;
    (*(void (__fastcall **)(__int64, char *))(*(_QWORD *)v5 + 2488LL))(v5, (char *)&v21 + 4);
    IOUSBDevice::GetLocationID(*(IOUSBDevice **)(v3 + 136));
    v8 = BYTE4(v21);
    v9 = a3;
    v10 = (unsigned __int8)v9;
    LODWORD(v11) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v3 + 136) + 2216LL))(
                     *(_QWORD *)(v3 + 136),
                     (unsigned __int8)v9);
    v7 = v11;
    if ( v11 )
      goto LABEL_20;
    LOBYTE(v21) = v8;
    if ( *(_BYTE *)v4 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    {
      v10 = v3;
      kernel_debug(0x52D9010u, v3, 0LL, 0LL, 0LL, 0LL);
    }
    IOSleep(300LL, v10);
    LODWORD(v12) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v3 + 136) + 2216LL))(*(_QWORD *)(v3 + 136), v9);
    v7 = v12;
    v6 = 0;
    if ( !v12 )
    {
      if ( *(_BYTE *)v4 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
        kernel_debug(0x52D9010u, v3, 0LL, 0LL, 1uLL, 0LL);
      LODWORD(v13) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)v3 + 904LL))(v3, 0LL);
      v14 = v13;
      LODWORD(v15) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v3 + 136) + 904LL))(
                       *(_QWORD *)(v3 + 136),
                       0LL);
      KernelDebugLogInternal(
        1LL,
        1431519814LL,
        "%s(%s)::GetConfigDescriptor - GetFullConfigDescriptor(%d) #2 returned NULL, trying ResetDevice and then trying again",
        v14,
        v15,
        v9);
      IOSleep(25LL, 1431519814LL);
      *(_BYTE *)(*(_QWORD *)(v3 + 160) + 2LL) = 1;
      v6 = -536870201;
      if ( v21 & 4 || (v6 = (*(int (**)(void))(**(_QWORD **)(v3 + 136) + 2232LL))()) != 0 )
      {
        if ( *(_BYTE *)v4 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
          kernel_debug(0x52D9010u, v3, 0LL, 0LL, 3uLL, 0LL);
        *(_BYTE *)(*(_QWORD *)(v3 + 160) + 2LL) = 0;
        v7 = 0LL;
        goto LABEL_21;
      }
      IOSleep(100LL, 1431519814LL);
      LODWORD(v16) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v3 + 136) + 2216LL))(
                       *(_QWORD *)(v3 + 136),
                       v9);
      v7 = v16;
      if ( v16 )
      {
LABEL_20:
        v6 = 0;
        goto LABEL_21;
      }
      if ( *(_BYTE *)v4 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
        kernel_debug(0x52D9010u, v3, 0LL, 0LL, 2uLL, 0LL);
      v7 = 0LL;
      LODWORD(v18) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)v3 + 904LL))(v3, 0LL);
      v19 = v18;
      LODWORD(v20) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v3 + 136) + 904LL))(
                       *(_QWORD *)(v3 + 136),
                       0LL);
      KernelDebugLogInternal(
        1LL,
        1431519814LL,
        "%s(%s)::ConfigureDevice GetFullConfigDescriptor(%d) #3 returned NULL, giving up",
        v19,
        v20,
        v9);
      v6 = -536854442;
    }
  }
LABEL_21:
  if ( *(_BYTE *)v4 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D9012u, v3, *(_QWORD *)(v3 + 136), v6, v7, 0LL);
  return v7;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;
// F4A0: using guessed type int __fastcall IOSleep(_QWORD, _QWORD);
// F4A8: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001E8A) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::ReConfigureDevice(IOUSBCompositeDriver *this)
{
  IOUSBCompositeDriver *v1; // r15@1
  __int64 v2; // rdi@1
  int v3; // er14@1
  int v4; // ebx@4
  __int64 v5; // rax@10
  __int64 v6; // rax@11
  __int64 v7; // rax@11
  __int64 v8; // rax@11
  __int64 v9; // rax@12
  char v11; // [sp+0h] [bp-30h]@1
  char v12; // [sp+1h] [bp-2Fh]@4
  __int16 v13; // [sp+2h] [bp-2Eh]@4
  __int16 v14; // [sp+4h] [bp-2Ch]@4
  __int16 v15; // [sp+6h] [bp-2Ah]@4
  __int64 v16; // [sp+8h] [bp-28h]@4

  v1 = this;
  bzero(&v11, 0x18uLL);
  v2 = *((_QWORD *)this + 17);
  v3 = -536870208;
  if ( v2 )
  {
    if ( (unsigned __int8)(*(int (__fastcall **)(__int64, IOUSBCompositeDriver *))(*(_QWORD *)v2 + 1504LL))(v2, v1)
      || (v3 = -536870203,
          (unsigned __int8)(*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD))(**((_QWORD **)v1 + 17)
                                                                                                 + 1488LL))(
                             *((_QWORD *)v1 + 17),
                             v1,
                             0LL,
                             0LL)) )
    {
      v11 = 0;
      v12 = 9;
      v13 = *((_BYTE *)v1 + 153);
      v14 = 0;
      v15 = 0;
      v16 = 0LL;
      v3 = 0;
      v4 = (*(int (__fastcall **)(_QWORD, char *, signed __int64, _QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 2424LL))(
             *((_QWORD *)v1 + 17),
             &v11,
             5000LL,
             0LL,
             0LL);
      if ( v4 )
      {
        (*(void (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD))(**((_QWORD **)v1 + 17) + 1496LL))(
          *((_QWORD *)v1 + 17),
          v1,
          0LL);
        v3 = v4;
      }
      else
      {
        if ( *((_BYTE *)v1 + 154) & 0x20
          && (unsigned __int8)(*(int (__cdecl **)(_QWORD, char *))(**((_QWORD **)v1 + 17) + 2256LL))(
                                *((_QWORD *)v1 + 17),
                                &v11) != 3
          && (*(int (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)v1 + 17) + 2144LL))(
               *((_QWORD *)v1 + 17),
               1LL) )
        {
          IOSleep(300LL, 1LL);
          v3 = (*(int (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)v1 + 17) + 2144LL))(
                 *((_QWORD *)v1 + 17),
                 1LL);
        }
        LODWORD(v5) = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 696LL))(
                        *((_QWORD *)v1 + 17),
                        "ExpressCardCantWake");
        if ( v5 )
        {
          LODWORD(v6) = (*(int (__cdecl **)(_QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 2264LL))(
                          *((_QWORD *)v1 + 17),
                          "ExpressCardCantWake");
          (*(void (__fastcall **)(__int64))(*(_QWORD *)v6 + 32LL))(v6);
          LODWORD(v7) = (*(int (__cdecl **)(_QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 2264LL))(
                          *((_QWORD *)v1 + 17),
                          "ExpressCardCantWake");
          (*(void (__fastcall **)(__int64, signed __int64, IOUSBCompositeDriver *, _QWORD))(*(_QWORD *)v7 + 1840LL))(
            v7,
            3758112784LL,
            v1,
            *((_QWORD *)v1 + 17));
          LODWORD(v8) = (*(int (__cdecl **)(_QWORD, signed __int64))(**((_QWORD **)v1 + 17) + 2264LL))(
                          *((_QWORD *)v1 + 17),
                          3758112784LL);
          (*(void (__fastcall **)(__int64))(*(_QWORD *)v8 + 40LL))(v8);
        }
        LODWORD(v9) = (*(int (__fastcall **)(_QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 696LL))(
                        *((_QWORD *)v1 + 17),
                        "kSuspendPort");
        if ( v9 == **(_QWORD **)off_3028[0] )
          v3 = (*(int (__fastcall **)(_QWORD, signed __int64))(**((_QWORD **)v1 + 17) + 2440LL))(
                 *((_QWORD *)v1 + 17),
                 1LL);
        (*(void (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD))(**((_QWORD **)v1 + 17) + 1496LL))(
          *((_QWORD *)v1 + 17),
          v1,
          0LL);
        (*(void (__cdecl **)(_QWORD, IOUSBCompositeDriver *))(**((_QWORD **)v1 + 17) + 32LL))(*((_QWORD *)v1 + 17), v1);
        (*(void (__fastcall **)(_QWORD, signed __int64, _QWORD, _QWORD))(**((_QWORD **)v1 + 17) + 1856LL))(
          *((_QWORD *)v1 + 17),
          3758112785LL,
          0LL,
          0LL);
        (*(void (__cdecl **)(_QWORD, signed __int64))(**((_QWORD **)v1 + 17) + 40LL))(
          *((_QWORD *)v1 + 17),
          3758112785LL);
      }
    }
  }
  return (unsigned int)v3;
}
// 3028: using guessed type __int64 off_3028[2];
// F4A0: using guessed type int __fastcall IOSleep(_QWORD, _QWORD);

//----- (00000000000020CA) ----------------------------------------------------
int __fastcall IOUSBCompositeDriver::SetConfiguration(IOUSBCompositeDriver *this, unsigned __int8 a2, unsigned __int8 a3)
{
  __int64 v3; // rax@1
  unsigned int v4; // er15@3
  int result; // eax@3
  unsigned int v6; // er15@12

  v3 = *((_QWORD *)this + 20);
  if ( v3 )
  {
    if ( *(_BYTE *)v3 )
    {
      *(_BYTE *)(v3 + 1) = 1;
      v4 = a3;
      result = (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 2528LL))(
                 *((_QWORD *)this + 17),
                 this,
                 a2,
                 a3,
                 1LL);
      if ( result != -536854442 && result != -536854435 )
      {
        if ( result )
        {
          IOSleep(100LL, this);
          result = (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 2528LL))(
                     *((_QWORD *)this + 17),
                     this,
                     a2,
                     v4,
                     1LL);
          if ( result != -536854442 && result != -536854435 && result )
          {
            IOSleep(25LL, this);
            *(_BYTE *)(*((_QWORD *)this + 20) + 2LL) = 1;
            result = (*(int (__cdecl **)(_QWORD))(**((_QWORD **)this + 17) + 2232LL))(*((_QWORD *)this + 17));
            if ( !result )
            {
              IOSleep(100LL, this);
              return (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD, signed __int64))(**((_QWORD **)this + 17) + 2528LL))(
                       *((_QWORD *)this + 17),
                       this,
                       a2,
                       v4,
                       1LL);
            }
LABEL_19:
            *(_BYTE *)(*((_QWORD *)this + 20) + 2LL) = 0;
            return result;
          }
        }
      }
      return result;
    }
    *(_BYTE *)(v3 + 1) = 0;
  }
  v6 = a3;
  result = (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD))(**((_QWORD **)this + 17) + 2240LL))(
             *((_QWORD *)this + 17),
             this,
             a2,
             a3);
  if ( result != -536854442 && result != -536854435 )
  {
    if ( result )
    {
      IOSleep(100LL, this);
      result = (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD))(**((_QWORD **)this + 17) + 2240LL))(
                 *((_QWORD *)this + 17),
                 this,
                 a2,
                 v6);
      if ( result != -536854442 && result != -536854435 && result )
      {
        IOSleep(25LL, this);
        *(_BYTE *)(*((_QWORD *)this + 20) + 2LL) = 1;
        result = (*(int (__cdecl **)(_QWORD))(**((_QWORD **)this + 17) + 2232LL))(*((_QWORD *)this + 17));
        if ( !result )
        {
          IOSleep(100LL, this);
          return (*(int (__fastcall **)(_QWORD, IOUSBCompositeDriver *, _QWORD, _QWORD))(**((_QWORD **)this + 17)
                                                                                       + 2240LL))(
                   *((_QWORD *)this + 17),
                   this,
                   a2,
                   v6);
        }
        goto LABEL_19;
      }
    }
  }
  return result;
}
// F4A0: using guessed type int __fastcall IOSleep(_QWORD, _QWORD);

//----- (00000000000022BE) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::ConfigureDevicePowerManagement(IOUSBCompositeDriver *this, IOService *a2)
{
  return 0LL;
}

//----- (00000000000022C6) ----------------------------------------------------
__int64 __usercall IOUSBCompositeDriver::FindPreferredConfiguration@<rax>(uintptr_t arg1@<rdi>, unsigned __int8 *a2@<rsi>, __int64 a3@<rax>)
{
  unsigned __int8 *v3; // r14@1
  uintptr_t v4; // r15@1
  __int64 v5; // r12@1
  __int64 v6; // rdi@4
  signed int v7; // ebx@4
  __int64 v8; // rax@14
  __int64 v9; // r8@14
  __int64 v10; // r9@14
  __int64 v11; // rax@14
  __int64 v12; // r13@14
  __int64 v14; // [sp-6h] [bp-30h]@1

  v14 = a3;
  v3 = a2;
  v4 = arg1;
  BYTE7(v14) = 0;
  v5 = off_3020[0];
  if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
  {
    a2 = (unsigned __int8 *)arg1;
    kernel_debug(0x52D9009u, arg1, *(_QWORD *)(arg1 + 136), 0LL, 0LL, 0LL);
  }
  *v3 = 0;
  v6 = *(_QWORD *)(arg1 + 136);
  v7 = -536870208;
  if ( v6 )
  {
    if ( (unsigned __int8)(*(int (__fastcall **)(__int64, unsigned __int8 *))(*(_QWORD *)v6 + 2312LL))(v6, a2) == 1 )
    {
      *v3 = 0;
      v7 = 0;
      if ( *(_BYTE *)v5 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      {
        v7 = 0;
        kernel_debug(0x52D9008u, v4, *(_QWORD *)(v4 + 136), 0LL, 0LL, 0LL);
      }
    }
    else
    {
      v7 = IOUSBCompositeDriver::FindConfigIndexFromPreferredConfiguration(v4, v3, (bool *)&v14 + 7);
      if ( !BYTE7(v14) && !v7 )
      {
        v7 = IOUSBCompositeDriver::FindConfigIndexFromPreferredInterface(v4, v3, (bool *)&v14 + 7);
        if ( !BYTE7(v14) && !v7 )
        {
          v7 = IOUSBCompositeDriver::FindConfigIndexFromPowerRequirements(v4, v3, (bool *)&v14 + 7);
          if ( v7 == -536854435 )
          {
            LODWORD(v8) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v4 + 136) + 904LL))(
                            *(_QWORD *)(v4 + 136),
                            0LL);
            KernelDebugLogInternal(
              1LL,
              1431519814LL,
              "USB Low Power Notice:  The device \"%s\" cannot be used because there is not enough power to configure it",
              v8,
              v9,
              v10);
            LODWORD(v11) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(v4 + 136) + 696LL))(
                             *(_QWORD *)(v4 + 136),
                             "Low Power Displayed");
            v12 = *(_QWORD *)off_3028[0];
            v7 = -536854435;
            if ( v11 != **(_QWORD **)off_3028[0] )
            {
              (*(void (__fastcall **)(_QWORD, signed __int64))(**(_QWORD **)(v4 + 136) + 2456LL))(
                *(_QWORD *)(v4 + 136),
                1LL);
              (*(void (__fastcall **)(_QWORD, _QWORD, _QWORD))(**(_QWORD **)(v4 + 136) + 616LL))(
                *(_QWORD *)(v4 + 136),
                "Low Power Displayed",
                *(_QWORD *)v12);
            }
          }
        }
      }
    }
  }
  if ( *(_BYTE *)v5 & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
    kernel_debug(0x52D900Au, v4, *(_QWORD *)(v4 + 136), *v3, v7, 0LL);
  return (unsigned int)v7;
}
// 3020: using guessed type __int64 off_3020[3];
// 3028: using guessed type __int64 off_3028[2];
// 3030: using guessed type __int64 off_3030;
// F4A8: using guessed type int __fastcall KernelDebugLogInternal(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000000000024BA) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPreferredConfiguration(uintptr_t arg1, unsigned __int8 *a2, bool *a3)
{
  bool *v3; // rbx@1
  __int64 v4; // rax@1
  unsigned __int8 v5; // al@2
  __int64 v6; // rax@3
  __int64 v7; // rcx@3
  __int64 result; // rax@3
  unsigned __int8 v9; // r12@5
  unsigned __int8 v10; // r13@6
  __int64 v11; // rax@6
  unsigned __int8 v12; // r14@9
  uintptr_t v13; // rcx@10

  v3 = a3;
  LODWORD(v4) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)arg1 + 696LL))(arg1, "Preferred Configuration");
  if ( v4 )
  {
    v5 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v4 + 312LL))(v4);
  }
  else
  {
    LODWORD(v6) = (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 696LL))(
                    *(_QWORD *)(arg1 + 136),
                    "Preferred Configuration");
    v7 = v6;
    result = 0LL;
    if ( !v7 )
      return result;
    v5 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v7 + 312LL))(v7);
  }
  v9 = v5;
  result = 0LL;
  if ( v9 )
  {
    v10 = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2312LL))();
    v11 = off_3020[0];
    if ( *(_BYTE *)off_3020[0] & 2 )
    {
      v11 = off_3030;
      if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
        kernel_debug(0x52D9008u, arg1, *(_QWORD *)(arg1 + 136), v9, 1uLL, 0LL);
    }
    v12 = 0;
    if ( v10 )
    {
      while ( 1 )
      {
        v13 = IOUSBCompositeDriver::GetConfigDescriptor(arg1, v11, v12);
        result = 3758097133LL;
        if ( !v13 )
          break;
        if ( *(_BYTE *)(v13 + 5) == v9 )
        {
          *a2 = v12;
          *v3 = 1;
          goto LABEL_15;
        }
        ++v12;
        v11 = v12;
        if ( v12 >= (unsigned int)v10 )
          goto LABEL_15;
      }
    }
    else
    {
LABEL_15:
      result = 0LL;
    }
  }
  return result;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;

//----- (00000000000025EA) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPreferredInterface(uintptr_t arg1, unsigned __int8 *a2, bool *a3)
{
  bool *v3; // r14@1
  uintptr_t v4; // r12@1
  __int64 v5; // rax@1
  signed int v6; // er13@1
  __int64 v7; // r15@2
  int v8; // eax@2
  uintptr_t v9; // rsi@3
  char v10; // bl@3
  unsigned __int8 v11; // r14@3
  unsigned int v12; // er13@3
  __int64 v13; // rax@4
  __int64 v14; // rax@5
  unsigned __int8 v15; // al@6
  unsigned int v16; // ebx@15
  unsigned __int8 v17; // r14@15
  uintptr_t v18; // r15@16
  __int64 v19; // rax@16
  __int64 v20; // rbx@16
  __int64 v21; // rax@17
  __int64 v22; // r13@17
  __int64 v23; // rax@17
  __int64 v24; // r12@17
  unsigned __int8 v25; // al@19
  __int64 v26; // rax@21
  __int64 v27; // r13@21
  __int64 v28; // rax@21
  __int64 v29; // rbx@21
  __int64 v30; // rdx@21
  __int64 v31; // rcx@21
  unsigned __int8 v32; // al@22
  unsigned __int8 v33; // al@24
  __int64 v34; // rax@25
  int v35; // edi@27
  __int16 v36; // ST24_2@27
  uintptr_t v37; // r12@28
  uintptr_t v38; // rax@29
  signed int v40; // [sp+8h] [bp-78h]@14
  unsigned __int8 v41; // [sp+Ch] [bp-74h]@13
  unsigned __int8 *v42; // [sp+10h] [bp-70h]@2
  bool *v43; // [sp+18h] [bp-68h]@2
  int v44; // [sp+24h] [bp-5Ch]@21
  char v45; // [sp+2Bh] [bp-55h]@14
  unsigned int v46; // [sp+2Ch] [bp-54h]@13
  unsigned int v47; // [sp+30h] [bp-50h]@16
  __int64 v48; // [sp+38h] [bp-48h]@10
  unsigned __int8 v49; // [sp+47h] [bp-39h]@16
  __int64 v50; // [sp+48h] [bp-38h]@16
  __int16 v51; // [sp+50h] [bp-30h]@28
  __int16 v52; // [sp+52h] [bp-2Eh]@28
  __int16 v53; // [sp+54h] [bp-2Ch]@28
  __int16 v54; // [sp+56h] [bp-2Ah]@28

  v3 = a3;
  v4 = arg1;
  LODWORD(v5) = (*(int (__fastcall **)(uintptr_t, _QWORD))(*(_QWORD *)arg1 + 696LL))(arg1, "Preferred Interface");
  v6 = 0;
  if ( v5 )
  {
    v42 = a2;
    v43 = v3;
    v7 = v5;
    v8 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v5 + 304LL))(v5);
    if ( v8 )
    {
      v9 = 0LL;
      v10 = 1;
      v11 = 0;
      v12 = v8;
      do
      {
        LODWORD(v13) = (*(int (__fastcall **)(__int64, uintptr_t))(*(_QWORD *)v7 + 488LL))(v7, v9);
        if ( v13 )
        {
          LODWORD(v14) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v13 + 520LL))(v13, "priority");
          if ( v14 )
          {
            v15 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v14 + 312LL))(v14);
            if ( !((unsigned __int8)-(v15 < 0xBu) & (unsigned __int8)-(v11 < (unsigned int)v15) & 1) )
              v15 = v11;
            v11 = v15;
          }
        }
        v9 = (unsigned __int8)v10++;
      }
      while ( (unsigned int)v9 < v12 );
      v48 = v7;
      if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
      {
        v9 = arg1;
        kernel_debug(0x52D9008u, arg1, v12, v11, 2uLL, 0LL);
      }
      v46 = v12;
      v6 = 0;
      v41 = v11;
      if ( v11 )
      {
        v45 = 1;
        v40 = 1;
        while ( 2 )
        {
          v16 = 0;
          v17 = 0;
          do
          {
            v47 = v16;
            v50 = 0LL;
            v18 = v4;
            v49 = (*(int (__fastcall **)(_QWORD, uintptr_t))(**(_QWORD **)(v4 + 136) + 2312LL))(
                    *(_QWORD *)(v4 + 136),
                    v9);
            v9 = v16;
            LODWORD(v19) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v48 + 488LL))(v48, v16);
            v20 = v19;
            if ( v19 )
            {
              LODWORD(v21) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v19 + 520LL))(v19, "priority");
              v22 = v21;
              v9 = (uintptr_t)"bInterfaceClass";
              LODWORD(v23) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v20 + 520LL))(v20, "bInterfaceClass");
              v24 = v23;
              if ( v22 )
              {
                if ( v23 )
                {
                  v25 = (*(int (__fastcall **)(__int64))(*(_QWORD *)v22 + 312LL))(v22);
                  if ( v25 )
                  {
                    if ( v25 == (unsigned __int8)v45 )
                    {
                      v44 = v25;
                      LODWORD(v26) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v20 + 520LL))(
                                       v20,
                                       "bInterfaceSubClass");
                      v27 = v26;
                      v9 = 0xFFFFuLL;
                      LODWORD(v28) = (*(int (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v20 + 520LL))(
                                       v20,
                                       "bInterfaceProtocol");
                      v29 = v28;
                      LOBYTE(v24) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v24 + 312LL))(v24);
                      LOWORD(v31) = -1;
                      if ( v27 )
                      {
                        v32 = (*(int (__fastcall **)(__int64, unsigned __int64, __int64, __int64))(*(_QWORD *)v27 + 312LL))(
                                v27,
                                0xFFFFuLL,
                                v30,
                                v31);
                        LOWORD(v31) = -1;
                        v9 = v32;
                      }
                      LOWORD(v24) = (unsigned __int8)v24;
                      if ( v29 )
                      {
                        v33 = (*(int (__fastcall **)(__int64, uintptr_t, __int64, __int64))(*(_QWORD *)v29 + 312LL))(
                                v29,
                                v9,
                                v30,
                                v31);
                        v9 = (unsigned int)v9;
                        LOWORD(v31) = v33;
                      }
                      v34 = off_3020[0];
                      if ( *(_BYTE *)off_3020[0] & 2 )
                      {
                        v34 = off_3030;
                        if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
                        {
                          v35 = v44 << 8;
                          v36 = v31;
                          kernel_debug(
                            0x52D9008u,
                            v18,
                            (unsigned __int16)v24 | v35 | (v47 << 16),
                            (unsigned __int16)v31 | ((_DWORD)v9 << 16),
                            3uLL,
                            0LL);
                          v9 = (unsigned int)v9;
                          LOWORD(v31) = v36;
                        }
                      }
                      v51 = v24;
                      v52 = v9;
                      v53 = v31;
                      v54 = -1;
                      v37 = 0LL;
                      if ( v49 )
                      {
                        do
                        {
                          v38 = IOUSBCompositeDriver::GetConfigDescriptor(v18, v34, v37);
                          v6 = -536870163;
                          if ( !v38 )
                            return (unsigned int)v6;
                          v9 = v38;
                          if ( !(*(int (__fastcall **)(_QWORD, uintptr_t, __int64, __int16 *, __int64 *))(**(_QWORD **)(v18 + 136) + 2192LL))(
                                  *(_QWORD *)(v18 + 136),
                                  v38,
                                  v50,
                                  &v51,
                                  &v50)
                            && v50 )
                          {
                            if ( *(_BYTE *)off_3020[0] & 2 && *(_DWORD *)off_3030 & 0xFFFFFFF7 )
                              kernel_debug(0x52D9008u, v18, v37, v40 | (v47 << 16), 5uLL, 0LL);
                            *v42 = v37;
                            *v43 = 1;
                            v6 = 0;
                            return (unsigned int)v6;
                          }
                          ++v37;
                          v34 = v49;
                        }
                        while ( (unsigned __int8)v37 < (unsigned int)v49 );
                      }
                    }
                  }
                }
              }
            }
            ++v17;
            v16 = v17;
            v4 = v18;
          }
          while ( v17 < v46 );
          ++v45;
          v40 = (unsigned __int8)v45;
          v6 = 0;
          if ( (unsigned __int8)v45 <= (unsigned int)v41 )
            continue;
          break;
        }
      }
    }
  }
  return (unsigned int)v6;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;

//----- (0000000000002992) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::FindConfigIndexFromPowerRequirements(uintptr_t arg1, unsigned __int8 *a2, bool *a3)
{
  unsigned __int8 v3; // r15@1
  unsigned __int8 v4; // cl@1
  __int64 result; // rax@1
  signed int v6; // er13@2
  signed int v7; // er14@2
  uintptr_t v8; // rbx@2
  uintptr_t v9; // rcx@3
  int v10; // er15@4
  bool *v11; // [sp+8h] [bp-38h]@1
  unsigned int v12; // [sp+10h] [bp-30h]@2
  int v13; // [sp+14h] [bp-2Ch]@2

  v11 = a3;
  v3 = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2312LL))();
  v4 = (*(int (**)(void))(**(_QWORD **)(arg1 + 136) + 2256LL))();
  result = 3758112861LL;
  if ( v3 )
  {
    v6 = -1;
    v7 = -536854435;
    v8 = 0LL;
    v13 = v4;
    result = v3;
    v12 = v3;
    do
    {
      v9 = IOUSBCompositeDriver::GetConfigDescriptor(arg1, result, v8);
      result = 3758097133LL;
      if ( !v9 )
        break;
      v10 = 4 * *(_BYTE *)(v9 + 8);
      if ( v13 != 3 )
        v10 = *(_BYTE *)(v9 + 8);
      if ( (*(int (__fastcall **)(_QWORD, _QWORD))(**(_QWORD **)(arg1 + 136) + 2272LL))(
             *(_QWORD *)(arg1 + 136),
             (unsigned __int8)v8) >= v10
        && v10 > v6 )
      {
        if ( *(_BYTE *)off_3020[0] & 2 )
        {
          if ( *(_DWORD *)off_3030 & 0xFFFFFFF7 )
            kernel_debug(0x52D9008u, arg1, v8, 0LL, 6uLL, 0LL);
        }
        *a2 = v8;
        *v11 = 1;
        v7 = 0;
        v6 = v10;
      }
      ++v8;
      result = (unsigned int)v7;
    }
    while ( (unsigned __int8)v8 < v12 );
  }
  return result;
}
// 3020: using guessed type __int64 off_3020[3];
// 3030: using guessed type __int64 off_3030;

//----- (0000000000002AB4) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver2(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 2);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002ACA) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver3(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 3);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002AE0) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver4(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 4);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002AF6) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver5(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 5);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B0C) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver6(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 6);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B22) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver7(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 7);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B38) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver8(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 8);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B4E) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver9(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 9);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B64) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver10(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 10);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B7A) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver11(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 11);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002B90) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver12(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 12);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002BA6) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver13(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 13);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002BBC) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver14(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 14);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002BD2) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver15(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 15);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002BE8) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver16(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 16);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002BFE) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver17(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 17);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002C14) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver18(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 18);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002C2A) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::_RESERVEDIOUSBCompositeDriver19(IOUSBCompositeDriver *this)
{
  return OSMetaClass::reservedCalled((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass, 19);
}
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002C40) ----------------------------------------------------
__int64 __fastcall AppleUSBComposite::MetaClass::~MetaClass(AppleUSBComposite::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000002C4A) ----------------------------------------------------
__int64 __fastcall IOUSBCompositeDriver::MetaClass::~MetaClass(IOUSBCompositeDriver::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000002C60) ----------------------------------------------------
__int64 `global constructor keyed to'_a_0()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(
    &AppleUSBComposite::gMetaClass,
    "AppleUSBComposite",
    &IOUSBCompositeDriver::gMetaClass,
    168LL);
  AppleUSBComposite::gMetaClass = off_43C0;
  OSMetaClass::OSMetaClass(&IOUSBCompositeDriver::gMetaClass, "IOUSBCompositeDriver", off_3008[0], 168LL);
  result = (__int64)off_4DE0;
  IOUSBCompositeDriver::gMetaClass = off_4DE0;
  return result;
}
// 3008: using guessed type _QWORD off_3008[6];
// 43C0: using guessed type __int64 (__fastcall *off_43C0[2])(AppleUSBComposite::MetaClass *__hidden this);
// 4DE0: using guessed type __int64 (__fastcall *off_4DE0[2])(IOUSBCompositeDriver::MetaClass *__hidden this);
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;
// F500: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000002CD0) ----------------------------------------------------
__int64 `global destructor keyed to'_a_0()
{
  OSMetaClass::~OSMetaClass((OSMetaClass *)&IOUSBCompositeDriver::gMetaClass);
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleUSBComposite::gMetaClass);
}
// 5190: using guessed type _QWORD AppleUSBComposite::gMetaClass;
// 51B8: using guessed type _QWORD IOUSBCompositeDriver::gMetaClass;

//----- (0000000000002CED) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 51E0: using guessed type int (*_realmain)(void);

//----- (0000000000002D07) ----------------------------------------------------
__int64 *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 2;
}
// 50A0: using guessed type __int64 kmod_info;

//----- (0000000000002D18) ----------------------------------------------------
__int64 *OSKextGetCurrentVersionString()
{
  return &kmod_info + 10;
}
// 50A0: using guessed type __int64 kmod_info;

//----- (0000000000002D29) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *((_DWORD *)&kmod_info + 3);
}
// 50A0: using guessed type __int64 kmod_info;

//----- (0000000000002D39) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 51E8: using guessed type int (*_antimain)(void);

// ALL OK, 85 function(s) have been successfully decompiled
